### ISSUE TITLE
Registry Title not working

### ISSUE THREAD

**Issue by distributorofpain** [Joxit/docker-registry-ui#108]
I am using docker-compose to start the registry and registryui with a nginx front end.

I tried using both types of yaml to get it to take the title, but it doesnt seem to take the setting.  It is connecting to the registry using the URL line, but thats about it.

```
version: '3'

services:
  registry:
    image: registry:2
    ports:
    - "127.0.0.1:5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry 1
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: 1
    volumes:
      - ./auth:/auth
      - ./data:/data
  registryui:
    image: joxit/docker-registry-ui:latest
    ports:
    - "127.0.0.1:8000:80"
    environment:
    - REGISTRY_TITLE=Registry 1
    - REGISTRY_URL="http://127.0.0.1:5000"
    - DELETE_IMAGES=true
```

**Comment by Joxit** [comment]
Hello, these options are for the **static** version only. Only tags with the `static` keywords.
So, you need to replace `latest` by `static` :slightly_smiling_face:

The original version of the interface allowed to use several registries and was not preconfigurable (you change the registry with some dialog windows).
The static version is here for only one registry, which why it needs configuration.

**Comment by distributorofpain** [comment]
oh, thanks for the clarification.  Unfortunately, it seems that if i try to use the static version with the docker-compose setup, it just wont launch(nginx says bad gateway).  Guessing it doesnt support CORS...  (at least with the configuration i am trying to use), i do send a username and password in the registry_url env variable.

**Comment by kctang** [comment]
Hi, I am using the static version with reverse proxy to my private docker repository. This part works.

However, like @distributorofpain, I am also not able to get `REGISTRY_TITLE` to take effect.

**Comment by Joxit** [comment]
Hello @kctang, may I have more intel ? did you try my examples ? https://github.com/Joxit/docker-registry-ui/blob/master/examples/ui-as-proxy/simple.yml ?

**Comment by kctang** [comment]
Hi @Joxit,

This is the docker-compose.yml I am using:

```
version: '3'

services:
  registry:
    image: registry:2.7.1
    networks:
      - local-network
    volumes:
      - /mnt/xxx:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:static
    environment:
      - DELETE_IMAGES=true
      - REGISTRY_TITLE=My Custom Registry
      - REGISTRY_URL=http://registry:5000
    depends_on: ['registry']
    networks:
      - local-network
      - ingress
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=ingress"
      - "traefik.http.routers.registry.rule=Host(`xxx.com`)"
      - "traefik.http.routers.registry.entrypoints=websecure"
      - "traefik.http.routers.registry.tls.certresolver=letsencrypt"
      - "traefik.http.routers.registry.middlewares=registry-auth"
      - "traefik.http.middlewares.registry-auth.basicauth.users=xxx:xxx"

networks:
  ingress:
    external: true
  local-network:
    external: false
```

Some additional, hopefully useful info to troubleshoot:

- I am using traefik (from an external docker compose on the same host) to route traffic to registry-ui.
- registry-ui reverse proxy to the registry service.
- based on current config, things work, except `REGISTRY_TITLE=My Custom Registry` does not seem to take effect.
