### ISSUE TITLE
Cannot delete image (There is no delete icon)

### ISSUE THREAD

**Issue by sadra** [Joxit/docker-registry-ui#123]
My `docker-compose.yml`

```
version: '2.0'
services:
  registry:
    image: registry:2.6.2
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry-config/htpasswd:/etc/docker/registry/htpasswd
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:static
    environment:
      - DELETE_IMAGES=true
      - REGISTRY_URL=http://registry:5000
      - REGISTRY_TITLE=OMG
    ports:
      - 4030:80
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
```

and the `registry-config/credentials.yml`

```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://localhost']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

When I log in to my registry-ui I can't see any **delete icon** and also the title was not changed too.

<img width="1159" alt="Screen Shot 2020-01-29 at 17 34 39" src="https://user-images.githubusercontent.com/18361407/73363270-aef89400-42bd-11ea-9052-55feb82ace1d.png">

Where is the problem? and what should I do?

**Comment by Joxit** [comment]
Hi,

I tried your configuration and the delete icon is present. Please pull the image`joxit/docker-registry-ui:static` again and check.
The important part to show the icon is `DELETE_IMAGES=true`.

If the bug persists, please use the [bug report template](https://github.com/Joxit/docker-registry-ui/issues/new?assignees=&labels=&template=bug_report.md&title=Cannot%20delete%20image%20%28There%20is%20no%20delete%20icon%29).

**Comment by gsugambit** [comment]
I did this and even though my credentials file has the https headers properties i still get the check your server error message
![image](https://user-images.githubusercontent.com/13861767/90357343-a892f500-e020-11ea-8025-72ea2b7f77b5.png)

**Comment by xoxefdp** [comment]
@gsugambit on your docker-compose.yml file you should specify a the next line as environment variable to the registry container. 
REGISTRY_STORAGE_DELETE_ENABLED='true'

**Comment by Joxit** [comment]
Yes, and also in your registry config
```yml
storage:
  delete:
    enabled: true
http:
  headers:
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
```
