### ISSUE TITLE
Add curl package to enable healthcheck

### ISSUE THREAD

**Issue by sadmin91** [Joxit/docker-registry-ui#128]
**Is your feature request related to a problem? Please describe.**
I am using your image for my personal use.
Actually, I build a custom image (using your image as source) in order to add curl package to create a healtcheck for my swarm service.
I think the addition of this package could help others users.

**Describe the solution you'd like**
Add curl package on Docker image

**Describe alternatives you've considered**
Build a custom Docker image to add this package

**Comment by 4n70w4** [comment]
+1 for healthcheck

**Comment by cnouguier** [comment]
Hi
As wget is shipped within the container, you can use the following command for the healthcheck: 
`wget -q --spider --tries=1 http://localhost:80`

Within a compose file:

```
healthcheck:
   test: ["CMD", "wget", "-q", "--tries=1", "--spider", "http://localhost:80"]
   interval: 30s
   timeout: 5s
   retries: 3
   start_period: 1m
```
