### ISSUE TITLE
 An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `http://101.200.133.34:8889` 

### ISSUE THREAD

**Issue by phpsxg** [Joxit/docker-registry-ui#140]
config.yaml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  headers:
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Headers: ['Origin','Accept','Content-Type','Authorization']
    Access-Control-Allow-Methods: ['GET','POST','PUT','DELETE','HEAD']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    Access-Control-Allow-Credentials: [true]

**Comment by Joxit** [comment]
Hello

Please write a correct issue using the template : https://github.com/Joxit/docker-registry-ui/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Griefed** [comment]
Since OP apparently can not be bothered to post a report using your temple, and I am having the same issue here, I'll go ahead and hiijack this thread:

name | about | title | labels | assignees
-- | -- | -- | -- | --
Bug report | Access-Control-Allow-Origin error no matter what the config says | Access-Control-Allow-Origin Error  | nginx, origin, config  |  

Hi, I use this docker registry UI and I have an issue...

## Bug description

I can browse the registry from localhost just fine, but whenever I try to access the UI from any other device on the network, I get the error message saying:
```An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to http://192.168.178.53```
The above IP is the one of my Raspberry Pi 3B+ on which I am trying to get this registry and UI up and running. 
Trying to access the UI from, say, 192.168.178.32, produces said error message.
I've tried ['*'], ['192,168.178.53'], ['192.168.178.32'] and combinations of the three, but so far, no dice.
## How to Reproduce

Steps to reproduce the behavior:
1. run 'docker-compose up -d' and wait till the containers have started
2. Go to http://ip.of.registry.host from any device on the network other than registry & ui host
3. Observe the Almigty-Neverending-Loading-Of-Death-Doom-And-Destruction™ 
4. See error meesage I posted in the 'Bug Description' part of this post


My docker-compose file
```yml
version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry-config/htpasswd:/etc/docker/registry/htpasswd

  ui:
    image: joxit/docker-registry-ui:arm32v7-static
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - URL=http://localhost:5000
    depends_on:
      - registry

```

My private docker registry credentials.yml configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd

```

## Expected behavior

I expected the WebUI to load and the login prompt to pop up, so I can login and browse the registry.

## Screenshots
![2020-07-31 20_44_37-Docker Registry UI](https://user-images.githubusercontent.com/44273438/89067035-c7ca2b00-d36e-11ea-800e-945cf6bb2ff4.png)
![2020-07-31 20_44_19-Docker Registry UI](https://user-images.githubusercontent.com/44273438/89067038-c862c180-d36e-11ea-9283-36620d2a9d9c.png)

If applicable, add screenshots to help explain your problem.

## System information

- OS: Raspbian GNU/Linux 10 (buster)

- Browser:
    - Name:  Chrome
    - Version: 84.0.4147.105 64bit
- Docker registry UI:
    - Version: [e.g. 1.4.0] Not sure where to get the version nr., sorry
    - Server: docker

    - Docker version: 19.03.12
    - Docker registry ui tag: arm32v7-static
    - OS/Arch: linux/arm32v7
    - Tools: docker-compose

## Additional context

I am trying to run the registry and ui at home and connect to it from a server via a secure VPN. Before moving to production, I'd like to test if this works, but so far, I can't even get this to work locally, on the same network. :D I'm at a loss here, I have no idea what to do. Help would be very much appreciated.
