### ISSUE TITLE
PULL_URL and REGISTRY_TITLE being ignored in my docker stack

### ISSUE THREAD

**Issue by Otlichno** [Joxit/docker-registry-ui#144]
Hello,
I have deployed the :static version of docker registry ui, with REGISTRY_TITLE and PULL_URL as additional environment variables for the service, and its seems to be ignored. The Registry title doesn't seem to show anywhere on the page, and the pull links are using the Registry URI as the pull location instead of the specified location.

## Bug description

The Copy docker pull command is using the Registry_UI host headers as they pull location instead of the one specified in PULL URL.
## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Deploy the stack with the below yml
2. Go to the endpoint and select an image
3. Click on copy pull command
4. See that the pull command is using the wrong Registry endpoint

For service bug, steps to reproduce the behavior:

My docker-compose file
```yml

```

My private docker registry configuration
```yml
version: '3.7'

x-default-opts:
  &default-opts
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
  # driver: "gelf"
  # options:
  #   gelf-address: "udp://127.0.0.1:5000"

services:

  joxit:
    <<: *default-opts
    image: joxit/docker-registry-ui:static
    deploy:
      replicas: 1
    networks:
      - registry_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=My Private Docker Repository
      - REGISTRY_URL=https://registry_service:8443
      - PULL_URL=build.private.internal:8443
networks:
  registry_net:
    driver: overlay
    name: registry_net
    external: true
```

## Expected behavior

I am expecting that the pull command copied to clip board would use the PULL_URL address instead of the registry UI's URL

## Screenshots
![Screen Shot 2020-08-26 at 9 00 12 AM](https://user-images.githubusercontent.com/3744983/91327893-0212c680-e77b-11ea-9db9-a39f116e46cf.png)

## System information

- OS: Fedora CoreOS
- Browser:
    - Name:  Chrome
    - Version: 84
- Docker registry UI:
    - Version: 1.5.0
    - Server: docker
    - Docker version: 19.03.11
    - Docker registry ui tag: static
    - OS/Arch: amd64
    - Tools: docker swarm
