### ISSUE TITLE
error in nginx

### ISSUE THREAD

**Issue by ortiga88** [Joxit/docker-registry-ui#153]
I have the following docker-compose:

```
version: "2"
services:
  registro:
    image: registry:2.7
    container_name: registro
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registro.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registro.key
    ports:
      - 443:443
      - 5000:5000
    volumes:
      - ./certs:/certs
      - ./data:/var/lib/registry
    restart: always



  registro-ui:
    image: joxit/docker-registry-ui:static
    container_name: resgistro-ui
    ports:
      - 80:80
    environment:
      - URL=http://192.168.2.158:443
#      - REGISTRY_SSL=true
      - REGISTRY_URL=https://registrodocker.es:443
#      - REGISTRY_STORAGE_DELETE_ENABLED=
    restart: on-failure

```
when I run it throws me the following error I don't know what I'm doing wrong?¿??

```
2020/11/06 13:19:40 [emerg] 1#1: host not found in upstream "registrodocker.es" in /etc/nginx/conf.d/default.conf:30
nginx: [emerg] host not found in upstream "registrodocker.es" in /etc/nginx/conf.d/default.conf:30

```
