### ISSUE TITLE
Error when listing library/* tags w/ fresh install

### ISSUE THREAD

**Issue by domibarton** [Joxit/docker-registry-ui#155]
Hi, I use this docker registry UI and I have an issue...

## Bug description

When I do a pull (e.g. `docker pull ubuntu`), I can see the fetched image in the UI.
However, when I click on it, then I see a lot of errors.

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Run `docker pull ubuntu`
2. Go to the UI
3. Click on `library/ubuntu`
4. See the following errors

```
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{}}]}
```

For service bug, steps to reproduce the behavior:

My docker-compose file
```yml
---
version: "3.8"

services:

  registry:
    image: registry:${REGISTRY_VERSION}
    container_name: registry
    environment:
      - REGISTRY_PROXY_REMOTEURL
      - REGISTRY_PROXY_USERNAME
      - REGISTRY_PROXY_PASSWORD
      - REGISTRY_STORAGE_DELETE_ENABLED="true"
    networks:
      - proxy
    volumes:
      - registry:/var/lib/registry
    labels:
      - traefik.http.routers.registry.rule=Host(`${REGISTRY_URL}`)
      - traefik.http.routers.registry.middlewares=private-service@file
    restart: always

  registry-ui:
    image: joxit/docker-registry-ui:static
    container_name: registry-ui
    environment:
      REGISTRY_URL: http://registry:5000
      PULL_URL: https://${REGISTRY_URL}
      DELETE_IMAGES: "true"
    networks:
      - proxy
    labels:
      - traefik.http.routers.registry-ui.rule=Host(`${REGISTRY_UI_URL}`)
      - traefik.http.routers.registry-ui.middlewares=private-service@file
    restart: always

volumes:
  registry:

networks:
  proxy:
    external: true
```

## Expected behavior

No errors should occur.

## Screenshots

![image](https://user-images.githubusercontent.com/4124099/99691339-6ba82580-2a89-11eb-86aa-1bc403e6f715.png)

## System information

- OS: Debian Buster
- Docker registry UI:
    - Version: latest
    - Server: docker

    - Docker version: 19.03.13
    - Docker registry ui tag: static
    - OS/Arch: linux/amd64
    - Tools: docker-compose

## Additional context

Appart from that, the UI works & looks fine 👍
