### ISSUE TITLE
Resource Is Busy

### ISSUE THREAD

**Issue by designermonkey** [Joxit/docker-registry-ui#164]
Hi, I use this docker registry UI and I have an issue...

Whenever I use a custom nginx config file mapped to the `default.conf` location, alongside the `REGISTRY_URL` env variable, I get the following error:

```
ui_1        | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
ui_1        | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
ui_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
ui_1        | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
ui_1        | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packages version
ui_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
ui_1        | /docker-entrypoint.sh: Launching /docker-entrypoint.d/90-docker-registry-ui.sh
ui_1        | sed: can't move '/etc/nginx/conf.d/default.confldbhFG' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1        | sed: can't move '/etc/nginx/conf.d/default.confpnlNJd' to '/etc/nginx/conf.d/default.conf': Resource busy
ui_1        | sed: can't move '/etc/nginx/conf.d/default.confimPfkA' to '/etc/nginx/conf.d/default.conf': Resource busy
```
I am trying to replicate ssl and auth as per the examples. I think it is related to the sed commands in the build process, but I know not why.

My docker-compose file
```yml
---
version: "3.6"
services:
  registry:
    image: registry:2
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml
    restart: always

  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 80:80
      - 443:443
    environment:
      REGISTRY_TITLE: My Docker Registry
      REGISTRY_URL: http://registry:5000
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./registry/htpasswd:/etc/nginx/auth/.htpasswd:ro
      - ./registry/cert.pem:/etc/nginx/certs/fullchain.pem:ro
      - ./registry/key.pem:/etc/nginx/certs/privkey.pem:ro
    depends_on:
      - registry
    restart: always
```

My private docker registry configuration
```yml
---
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ["https://my-domain.local"]
    Access-Control-Allow-Methods: ["HEAD", "GET", "OPTIONS", "DELETE"]
    Access-Control-Allow-Headers: ["Authorization", "Accept"]
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ["Docker-Content-Digest"]
```

## Expected behavior

I would hope for the container to start as per the examples.
