### ISSUE TITLE
docker-registry-ui and keyloak auth 

### ISSUE THREAD

**Issue by vitalybrandes** [Joxit/docker-registry-ui#165]
Is there any additional auth modules except basic-realm ?
I am running registry with keycloak SSO  and it will be great if i can login to UI with the same user.

Now , when i am trying to setup both, keyloack and basic-realm, i got issue with Registry (cannot login) as well with UI , can not login.
maybe any workaround?
my docker-compose file;

```
registry:
    image: "registry:2.7.1"
    ports:
      - "5000:5000"
    restart: "always"
    volumes:
      - ./config/certs:/opt/certs:z
      - ./data/registry:/data:z
      - ./config/settings/credentials.yml:/etc/docker/registry/config.yml
      - ./config/settings/htpasswd/htpasswd:/etc/docker/registry/htpasswd
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /opt/certs/registry_trust_chain.pem
      REGISTRY_AUTH_TOKEN_REALM: http://localhost:8011/auth/realms/docker-registry/protocol/docker-v2/auth
      REGISTRY_AUTH_TOKEN_SERVICE: docker-registry
      REGISTRY_AUTH_TOKEN_ISSUER: http://localhost:8011/auth/realms/docker-registry
    networks: 
      - proxy

  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8009:80
    environment:
      - REGISTRY_TITLE=Dip-Tech Docker Registry
      - URL=http://localhost:5000
    depends_on:
      - registry
    networks: 
      - proxy
```

**Comment by vitalybrandes** [comment]
change the auth on config.yml file to:
```
auth:
  token:
    autoredirect: true
    realm: http://localhost:8011/auth/realms/docker-registry/protocol/docker-v2/auth
    service: docker-registry
    issuer: http://localhost:8011/auth/realms/docker-registry
    rootcertbundle: /opt/certs/registry_trust_chain.pem
```

get error from the UI:
`{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"registry","Class":"","Name":"catalog","Action":"*"}]}]}`

login to registry:5000 ok using keyloak as auth realm.

Is it that docker-registry-ui not support token auth???
