### ISSUE TITLE
thpasswd login\pass is not valid

### ISSUE THREAD

**Issue by offlinejke** [Joxit/docker-registry-ui#173]
Htpasswd file is visible in the container, during authorization it does not accept my username / password.
```
   registry-server:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/etc/docker/registry/config/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry/config/htpasswd:/etc/docker/registry/htpasswd

  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://10.10.5.187:5000
      #- REGISTRY_AUTH=htpasswd
      #- REGISTRY_AUTH_HTPASSWD_PATH=./registry/config/htpasswd
      #- REGISTRY_AUTH_HTPASSWD_REALM: Registry
    depends_on:
      - registry-server
```
