### ISSUE TITLE
blob upload unknown

### ISSUE THREAD

**Issue by offlinejke** [Joxit/docker-registry-ui#174]
Hi, I've already spent a whole day configuring the register with UI. As a result, password authentication does not work, the login\ password is simply not accepted by the system. Then I push the image, and take ```blob upload unknown```.
UI said ```0 images```, although I noticed that the images are poured into the directory specified in the compose file.
```
  registry-server:
    image: registry:2
    ports:
      - 5000:5000
    #environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /etc/docker/registry/auth/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /etc/docker/registry/auth/domain.key
      #- REGISTRY_AUTH=htpasswd
      #- REGISTRY_AUTH_HTPASSWD_PATH=/etc/docker/registry/config/htpasswd
      #- REGISTRY_AUTH_HTPASSWD_REALM=Registry
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry/config/htpasswd:/etc/docker/registry/htpasswd
    networks:
      vpcbr:
        ipv4_address: 172.10.0.11

  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Whaleapp Hub
      - REGISTRY_URL=http://10.10.5.187:5000
      #- REGISTRY_AUTH=htpasswd
      #- REGISTRY_AUTH_HTPASSWD_PATH=./registry/config/htpasswd
      #- REGISTRY_AUTH_HTPASSWD_REALM: Registry
    depends_on:
      - registry-server
    networks:
      vpcbr:
        ipv4_address: 172.10.0.12
```
credentials.yml
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  secret: asecretforlocaldevelopment
  host: https://hub.office.whaleapp.team
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://localhost']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [none]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    
```
