### ISSUE TITLE
Caching issue with nginx causes freeze and high CPU usage

### ISSUE THREAD

**Issue by ViRb3** [Joxit/docker-registry-ui#183]
## Bug description

There seems to be a cache issue between this project and nginx, causing freeze and high CPU usage.

### Method 1
1. Go to any image
2. Click the 'History' button of any tag
3. Click the back/left arrow of the UI to go back
4. Repeat this a few times, usually once is enough

### Method 2
1. Go to any image
2. Delete any tag
3. Refresh the page

In both cases, the image will show '?' on each column, the UI will become completely unresponsive (freeze), and the browser will clog one CPU core to 100%. I discovered that if I clear the cache, the problem always goes away until it is reproduced again via one of the methods above. In my nginx reverse proxy,, I added the following as a workaround:
```nginx
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
```
## System information

- OS: Ubuntu 20.04
- Browser:
    - Name:  Brave
    - Version: 1.23.75, Chromium 90.0.4430.93
- Docker registry UI:
    - Version: 2.0.0
    - Server: Docker
- Docker:
    - Docker version: 19.03.8
    - Docker registry ui tag: 2.0
    - OS/Arch: linux/arm64
    - Tools: docker-compose

**Comment by Joxit** [comment]
Hi, thank you for using my project :smile: 

Oh, that's strange... Did you try a mix of `NGINX_PROXY_PASS_URL` and `NGINX_PROXY_HEADERS` for your workaround ? Or you added the configuration on another nginx reverse proxy ?

**Comment by ViRb3** [comment]
I have another (a global) nginx instance that covers all of the services on my server, this service included. It wraps them in HTTPS, etc. I added my workaround directly to my global nginx instance.

For your project, I used the following Docker Compose definition:

```yml
  registry-ui:
    image: joxit/docker-registry-ui:2.0
    container_name: registry-ui
    environment:
      - REGISTRY_TITLE=REDACTED
      - PULL_URL=REDACTED
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry
      - registry-ui-nginx
```
