### ISSUE TITLE
Support needed

### ISSUE THREAD

**Issue by gauravmeena83** [Joxit/docker-registry-ui#185]
I am following the example for kubernetes given here [https://github.com/Joxit/docker-registry-ui/tree/main/examples/kubernetes]
haven't changed anything from there except environment for the registry-ui
```
     containers:
        - name: registry-ui
          image: "docker.io/joxit/docker-registry-ui:2.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: REGISTRY_URL
              value: "http://registry.cluster.local/"
            - name: REGISTRY_TITLE
              value: "Docker-registry UI"
            - name: DELETE_IMAGES
              value: "false"
            - name: SINGLE_REGISTRY
              value: "true"
```
I have default nginx-ingress defined
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  name: docker-registry
  namespace: docker-registry
spec:
  ingressClassName: "nginx"
  rules:
  - host: registry.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker-registry
            port: 
              number: 5000

  - host: registry-ui.cluster.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: docker-registry-ui
            port: 
              number: 80
```

The docker-registry works, but the UI doesn't. Its not able to connect to backend server of registry. The error is
```
An error occured: Check your connection and your registry must have `Access-Control-Allow-Origin` header set to `http://registry-ui.cluster.local`
```

The defalt configmap that you have provided, does have a value, which I believe should match
```
Access-Control-Allow-Origin: ['*']
```
I have tried two seperate ingresses for the services, and env value of REGISTRY_URL to be http://docker-registry:5000/ as well as http://docker-registry.docker-registry.svc.cluster.local/ ... without any benefit..... I also tried putting both the container in a single pod, and tried with http://localhost:5000/, that too didn't work.

Can you help? Also do lemme know the best possible solution, so that log for that particular setting can be shared. For this particular setup, logs of docker-registry-ui pod are
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: ipv6 not available
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/90-docker-registry-ui.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
172.16.44.6 - - [03/May/2021:13:37:37 +0000] "GET / HTTP/1.1" 200 1438 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "192.168.6.33"
172.16.44.6 - - [03/May/2021:13:37:41 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "192.168.6.33"
172.16.44.6 - - [03/May/2021:13:37:41 +0000] "GET /docker-registry-ui.js HTTP/1.1" 304 0 "http://registry-ui.cluster.local/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" "192.168.6.33"
```
my nginx-ingress-controller is on 192.168.6.33.
