### ISSUE TITLE
Docker Registry UI 2.0.0 does not display date, image name and history.

### ISSUE THREAD

**Issue by Tibor17** [Joxit/docker-registry-ui#190]
Hi, I use this docker registry UI `2.0.0` and I have an issue where the `date` is not displayed for `ago`, `name` and `history` is not displayed either.

![docker-registry-ui](https://user-images.githubusercontent.com/1045063/117471669-67e55e00-af58-11eb-90fd-72d38642bf58.jpg)

I am using standard steps.

Configuring the registries `/etc/docker/daemon.json` as follows:

```
{
    "registry-mirrors" : ["https://172.18.105.28:5000"]
}
```

The IP address `172.18.105.28` has the host name `industry.issk.sk`.

Registry config file `/root/docker/registry/config.yml`:

```
version: 0.1
log:
  fields:
    service: registry-srv
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['industry.issk.sk:5002']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
```

Starting the registry:
```
$ docker service create \
--name registry-srv \
--mount type=bind,src=/mnt/lnet-data/docker-registry,dst=/var/lib/registry \
--mount=type=bind,src=/root/docker/certs,dst=/certs \
--mount=type=bind,src=/root/docker/registry/config.yml,dst=/etc/docker/registry/config.yml \
-e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
-e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.cert \
-e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
-e REGISTRY_STORAGE_DELETE_ENABLED=true \
-p 5000:5000 \
--network docker-registry-net \
registry:2
```

Starting the registry UI:

```
$ docker pull joxit/docker-registry-ui:2.0-debian
$ docker service create  \
--name registry-ui \
--mount=type=bind,src=/root/docker/certs,dst=/etc/nginx/certs \
-e REGISTRY_TITLE="Docker Registry" \
-e REGISTRY_URL="https://industry.issk.sk:5000" \
-e DELETE_IMAGES=true \
-p 5002:80 \
--network docker-registry-net \
joxit/docker-registry-ui:2.0-debian
```

Thx for the help!
T
