### ISSUE TITLE
Modify port in example : proxy-headers

### ISSUE THREAD

**Issue by felixcapuano** [Joxit/docker-registry-ui#191]
Hi, 
It is certainly not very complicated but I am trying to modify the port of the nginx server in the [proxy headers](https://github.com/Joxit/docker-registry-ui/tree/main/examples/proxy-headers) example. I would like expose port 8000 instead of port 80. I tried to modify the port in the docker-compose.yml but when I do that the UI is still accessible but I can no longer push the images. 

So I think my problem comes from the communication between registry and the UI.
I have not found any solution and it is surely not very complicated.

My modification of the docker-compose.yml.
```yaml
version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config/credentials.yml:/etc/docker/registry/config.yml
      - ./registry-config/htpasswd:/etc/docker/registry/htpasswd
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8000:80 # instead of 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - NGINX_PROXY_HEADER_X_Forwarded_For=$$proxy_add_x_forwarded_for
      - SINGLE_REGISTRY=true
    volumes:
      - ./nginx.env:/etc/nginx/.env
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net
```

The error then I trying to push a images in a repo.
```bash
> docker push localhost:8000/backend:latest
The push refers to repository [localhost:8000/backend]
f31b5bd6df06: Pushing [==================================================>]  3.906MB/3.906MB
71818d1a0115: Pushing [==================================================>]  8.933MB/8.933MB
a402f7a25c54: Pushing [==================================================>]  16.16kB
c9b55b4f8fe8: Pushing [==================================================>]  725.1kB/725.1kB
070b66cea4a0: Retrying in 1 second
7802950192bc: Waiting
119ee89d56bc: Waiting
b2d5eeeaba3a: Waiting
dial tcp [::1]:80: connect: connection refused
```
Thank you.
