### ISSUE TITLE
Delete button is displayed when DELETE_IMAGES is set to false

### ISSUE THREAD

**Issue by zhsj** [Joxit/docker-registry-ui#192]
Hi, I use this docker registry UI and I have an issue...

## How to Reproduce

1. Go to image tag list
2. Found the delete button is there

![image](https://user-images.githubusercontent.com/227180/118912094-d7e0e480-b959-11eb-9faa-2b85755739c5.png)

The index.html says the DELETE_IMAGES value is applied.

![image](https://user-images.githubusercontent.com/227180/118912115-e0391f80-b959-11eb-8b74-3ca8d095a14b.png)

My registry has enabled deletion, but I don't want it shown on web page.

For service bug, steps to reproduce the behavior:

I'm using ansible, but it can be easily translated to other ways.

```
- name: run registry
  docker_container:
    name: registry
    restart_policy: always
    image: "{{ registry_image }}"
    ports:
      - 0.0.0.0:5001:5000/tcp
    volumes:
      - "{{ docker_storage }}/registry:/var/lib/registry"
    env:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
  become: yes

- name: run registry ui
  docker_container:
    name: registry-ui
    restart_policy: always
    image: "{{ registry_ui_image }}"
    ports:
      - 0.0.0.0:5002:80/tcp
    env:
      PULL_URL: http://{{ ansible_default_ipv4.address }}:5001
      NGINX_PROXY_PASS_URL: http://{{ ansible_default_ipv4.address }}:5001
      SINGLE_REGISTRY: "true"
  become: yes

```

## Expected behavior

No delete button on tag list page.

## Screenshots

See above.

## System information

- Browser:
    - Name: Chromium
    - Version: 89.0.4389.114
- Docker registry UI:
    - Version: 2.0.1
    - Server: docker
    - Docker version: 19.03.15
    - Docker registry ui tag: joxit/docker-registry-ui:2.0
    - OS/Arch: linux/amd64
    - Tools: ansible+docker
