### ISSUE TITLE
Kubernetes: open() "/usr/share/nginx/html/index.html" failed (13: Permission denied)

### ISSUE THREAD

**Issue by asperan** [Joxit/docker-registry-ui#203]
Hi, I use this docker registry UI in a kubernetes cluster and I setup an Ingress to access the UI.

## Bug description
The registry UI cannot be accessed from a fresh pod because the user `nginx` cannot access the website folder (files are owned by `root:root` rather than `nginx:nginx`) and gives a 403 page.

After executing `chown` into the pod to change the files owner, the UI becomes accessible, so I guessed this is a owner problem.

## How to Reproduce

For service bug, steps to reproduce the behavior:
My docker registry deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2.7.1
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: registry-volume
            mountPath: POD_REGISTRY_VOLUME_PATH
        env:
        - name: REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin
          value: "['*']"
      volumes:
      - name: registry-volume
        nfs:
          path: "NFS_REGISTRY_VOLUME_PATH"
          server: "NFS_SERVER"
```

My registry UI deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-frontend
  labels:
    app: registry-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-frontend
  template:
    metadata:
      labels:
        app: registry-frontend
    spec:
      containers:
      - name: registry-frontend
        image: joxit/docker-registry-ui:arm64v8
        ports:
        - containerPort: 80
        env:
        - name: "NGINX_PROXY_PASS_URL"
          value: "http://docker-registry-svc:5000" # This is a kubernetes service which points to the registry pods
        - name: "REGISTRY_TITLE"
          value: "HDR - Home Docker Registry"
        - name: SINGLE_REGISTRY
          value: "true"
```

## Expected behavior

Being able to view the UI instead of getting a 403 page.

## Screenshots
The owner status on a fresh pod:
![freshPodOwner](https://user-images.githubusercontent.com/14941985/128142339-8d4d98ea-078f-4da3-8396-aa3274d54bf7.png)

403 forbidden:
![403](https://user-images.githubusercontent.com/14941985/128142435-c18965b4-7473-44cf-8b95-65f0e77c9883.png)

Pod logs:
![podLogs](https://user-images.githubusercontent.com/14941985/128142551-a301ba7e-f83b-47ca-a1d5-3d267d4976b8.png)

The new owner (changed with `chown nginx:nginx ./*` inside `/usr/share/nginx/html`):
![newOwners](https://user-images.githubusercontent.com/14941985/128141695-c83ebb3b-da56-4617-bb13-aa173c7acaeb.png)

UI after changing owner:
![CorrectBehaviour](https://user-images.githubusercontent.com/14941985/128141450-d042ba2b-90f1-4e85-8d4d-68298671425a.png)

## System information

- Docker registry UI:
    - Version: 2.0.8
    - Server: docker (container inside pod)
    - Docker version: 20.10.7
    - Docker registry ui tag: arm64v8
    - OS/Arch: [Debian Buster based ARM64 build](https://github.com/ayufan-rock64/linux-build)
    - Tools: kubernetes

## Additional context

I'd say that to resolve this issue it should be enough to add `--chown nginx:nginx` the the relevant line of the Dockerfile.

I can also open a PR to change the Dockerfile if needed.

Btw, congrats for this amazing and useful UI!
