### ISSUE TITLE
Document using the app in a subPath

### ISSUE THREAD

**Issue by manelclos** [Joxit/docker-registry-ui#221]
Hi, here is an ingress for using docker-registry-ui in a subpath, in the same domain as the private registry.

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: docker-registry-ui
  namespace: docker-registry
spec:
  rules:
  - host: registry.example.com
    http:
      paths:
      - pathType: Prefix
        path: /ui/(.*)
        backend:
          service:
            name: docker-registry-ui
            port:
              number: 80
```

**Comment by Joxit** [comment]
Hi there, thanks for using my project :smile:
You can also create PR with a full k8s example in the `examples` folder

**Comment by cawoodm** [comment]
Unfortunately this does not work with a traefik ingress controller (i.e. by replacing `nginx.ingress.kub...` with `traefik.ingress.kub...`).

I have posted the question [here](https://stackoverflow.com/questions/70789020/traefik-ingress-rewrite-target-does-nothing).

Any help would be appreciated.

@Joxit Your documentation suggests running the registry and ui on the same domain. How are you doing this?

**Comment by Joxit** [comment]
In fact, my docker registry and ui are not on kubernetes, everything is configured with docker compose with our old `nginx.conf` :smile:.

Did you find your answers ?

**Comment by cawoodm** [comment]
Yes thanks, it's not ideal but I run the registry on /v2/ and the UI on /:

## Ingress Resource
```yaml
spec:
  rules:
  - host: repo.my.com
    http:
      paths:
      - backend:
          service:
            name: registry-docker-registry
            port:
              number: 5000
        path: /v2/
        pathType: Prefix
      - backend:
          service:
            name: docker-registry-ui
            port:
              number: 80
        path: /
        pathType: Prefix
```
