### ISSUE TITLE
Not able to push image to registry with own SSL certificate. 

### ISSUE THREAD

**Issue by iamakashk** [Joxit/docker-registry-ui#223]
Hi I am using following docker compose file to run registry and ui ,

```
version: '3.0'
services:
  unified-registry:
    image: registry:2.7
    restart: always
    volumes:
      - ./registry-data:/var/lib/registry
        #      - ./config.yml:/etc/docker/registry/config.yml:ro    
        #    volumes:
        #      - ./registry-data:/var/lib/registry
    networks:
      - registry-ui-net
  ui:
    image: joxit/docker-registry-ui:latest
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Unified Private Docker Registry
      - DELETE_IMAGES=true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/my.crt:/etc/nginx/certs/my.crt
      - ./nginx/my.key:/etc/nginx/certs/my.key
      - ./registry-data:/var/lib/registry
    ports:
      - 5001:80
      - 443:443
    depends_on:
      - unified-registry
    networks:
      - registry-ui-net
networks:
  registry-ui-net:
```

When I am trying to push image to this repository I am getting following error, 

`Get https://MY_DOMAIN_NAME/v2/: x509: certificate signed by unknown authority`

I checked logs for registry and it shows following log line, 
`2021/12/25 06:24:03 http: TLS handshake error from IP:42340: remote error: tls: bad certificate`

Is there any other setting needs to be changed to make this work with SSL certificate?
