### ISSUE TITLE
Can't delete images

### ISSUE THREAD

**Issue by owenyoungman-coderus** [Joxit/docker-registry-ui#229]
Hello! I have seen similar issues raised but can't seem to find a solution that has worked. If anyone could help I would greatly appreciate it! I am using an insecure registry hosted locally. All machines have been configured to allow access to this registry and pushing/pulling is working fine. I'm using docker-compose to run

This is my dockerfile:

```
version: '2.0'
services:
  registry:
    image: registry:2.6.2
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_HEADERS_ACCESS-CONTROL-ALLOW-ORIGIN=['*']
      - REGISTRY_STORAGE_DELETE_ENABLED="true"
      - REGISTRY_HTTP_HEADERS_ACCESS-CONTROL-ALLOW-METHODS=['HEAD', 'GET', 'OPTIONS', 'DELETE']
      - REGISTRY_HTTP_HEADERS_ACCESS-CONTROL-EXPOSE-HEADERS=['Docker-Content-Digest']
      - X-CONTENT-TYPE-OPTIONS=[nosniff]
    volumes:
      - ./registry-data:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:1.5-static
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Internal Docker Registry
      - REGISTRY_URL=http://registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:


```

I don't know how many of these settings are unnecessary, but I was trying everything!

The error I am getting when I try and delete an image is `{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}`

If anyone can see my mistake or has a working dockerfile that I could replace with mine then I would be very grateful! Thanks in advance!
