### ISSUE TITLE
JS browser error when deleting image

### ISSUE THREAD

**Issue by shukriadams** [Joxit/docker-registry-ui#233]
When I attempt to delete an image, I get the following Javascript error in my browser :

```
docker-registry-ui.js:20 Uncaught ReferenceError: Cannot access 's' before initialization
    at Object.deleteImage (docker-registry-ui.js:20:81908)
    at docker-registry-ui.js:20:81739
    at Set.forEach (<anonymous>)
    at Object.deleteImages (docker-registry-ui.js:20:81722)
    at HTMLElement.root.onclick (docker-registry-ui.js:20:17726)
```
This seems to prevent delete from working. Error happens consistently on all button clicks, and on Chrome and Firefox.

I get this error on `joxit/docker-registry-ui:2.0.9`, and `joxit/docker-registry-ui:2.1.0`.

## How to Reproduce

- Go to docker-reg-ui website
- Select an image to get to tag list
- click on "delete" icon next to a tag
- nothing happens at this point, but JS error can be seen in browser console

**Comment by SasoPavlic** [comment]
I have the same issue. The weirdest thing is the following:
URL= http://xxx.xxx.xxx.xxx:5000  <- docker registry is running on my server

- When running image locally on my laptop and setting URL, then deletion works normally.
- When running image on my server and setting URL to the same value as before, then deletion does not work.

Version info:
Docker Registry UI 2.1.0
Docker registry: 9 months old, not sure how to check...

**Comment by Joxit** [comment]
Hello, thank you for using my project :smile: 

Can you give me your: 
- docker-registry-ui configuration (environments)
- docker registry configuration (environments and yaml)
- anonymized hostname + port of your UI
- anonymized hostname + port of your registry

**Comment by SasoPavlic** [comment]
Thank you for looking into issues 😊

My setup:
**simple.yml** looks like that:

```
version: '2.0'
services:
  registry:
    image: registry:2.7
    ports:
      - 5000:5000
#    volumes:
#      - ./registry-data:/var/lib/registry
#      - ./registry-config/simple.yml:/etc/docker/registry/config.yml
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE= Private Registry
      - SINGLE_REGISTRY=false
      - DELETE_IMAGES=true
      - REGISTRY_URL=http://XXX.XXX.XXX.XXX:5000/

    depends_on:
      - registry
```
yaml is from: [Docker Registry Static as standalone example](https://github.com/Joxit/docker-registry-ui/tree/main/examples/ui-as-standalone).

When I used volumes, I was getting [issues ](https://stackoverflow.com/questions/64560653/cannot-start-service-prometheus-oci-runtime-error-container-linux-go235-star)such as "container init exited prematurely" (from example). As a result, I comment them out. I hope this isn't the fundamental cause of the problem in the first place...

anonymized hostname + port of your UI = XXX.XXX.XXX.XXX:8080
anonymized hostname + port of your registry = XXX.XXX.XXX.XXX:5000

Let me explain one more time the deletion issue and my current solution to it:

- If I run `docker-compose -f simple.yml up` on my server, everything setups normally except deletion does not work (above JS error in console) Figure 1.
- If I run `docker-compose -f simple.yml up` (with localhost IP in REGISTRY_URL) on my laptop everything works normally.

Solution on deleting images on my server: 

1. Run `docker-compose -f simple.yml up` on my server and laptop (with the corresponding REGISTRY_URL)
2. Navigate on my laptop to localhost:8080 and change server URL to server IP (XXX.XXX.XXX.XXX:5000) in UI.
3. Delete selected image from the server

Figure 1
![workflow](https://user-images.githubusercontent.com/24464688/155320018-21ce33af-9d57-44b7-882c-8cced5deb4aa.jpg)


I hope this helps.

**Comment by Joxit** [comment]
Hi, sorry I can't reproduce your issue.

First of all, your `simple.yml` should not work without the `Access-Control-Allow-Origin` configuration for your registry. This configuration is stored in the commented `registry-config/simple.yml` file.

The bin is grey only when I can't retrieve the image digest and this happens only when the header `Docker-Content-Digest` is not present (=> missing `Access-Control-Expose-Headers` on your registry configuration) or when `crypto` function is not present on your browser (=> Old version or IE / old Edge)

Is this still happening after this fix: https://github.com/Joxit/docker-registry-ui/issues/226 ?

**Comment by DoWhileGeek** [comment]
I have carbon copy the same error messages.

**Comment by DoWhileGeek** [comment]
added these settings to my registry config, worked:
```
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    ```

I assume either `Docker-Content-Digest` or allowing the delete method did the trick.

**Comment by DoWhileGeek** [comment]
@SasoPavlic I'd suggest looking into your registry config, ensure the above variables are set, in addition to the origin header

**Comment by SasoPavlic** [comment]
Thank you @Joxit and @DoWhileGeek , with your suggestions I've managed to set it up correctly.

The major hustle was to figure out how I can set up volumes on RHEL Linux. As you mentioned volumes are necessary to update config.yml. The trick was to use **z** parameter ([Docker issue](https://stackoverflow.com/a/31334443/6152465)).

```
version: '2.0'
services:
  registry:
    ports:
      - 5000:5000
    volumes:
      - /app/private_hub/registry-data:/var/lib/registry:z
      - /app/private_hub/registry-config/simple.yml:/etc/docker/registry/config.yml:z
    container_name: backend_registry
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8080:80
    environment:
      - REGISTRY_TITLE= Private Registry
      - SINGLE_REGISTRY=false
      - DELETE_IMAGES=true
      - REGISTRY_URL=http://XXX.XXX.XXX.XXX:5000/

    depends_on:
      - registry

    container_name: frontend_registry
```
