### ISSUE TITLE
nginx crashes since 2.2.0 when overriding default.conf

### ISSUE THREAD

**Issue by utrotzek** [Joxit/docker-registry-ui#247]
Hi, I use this docker registry UI and I have an issue...

## Bug description

Since version 2.2.0 the nginx crashes with the following error when the dafault.conf is mounted into the container:

`sed: can't move '/etc/nginx/conf.d/default.confLFCogB' to '/etc/nginx/conf.d/default.conf': Resource busy`

Obviously this has something to do with a change of the underlying nginx image that you are using. I could not figure out what exactly changed there. 

I would suggest to adjust the examples.  https://github.com/Joxit/docker-registry-ui/blob/main/examples/read-only-auth/docker-compose.yml#L19

Maybe you could change it like this. I worked around this by simple creating an own Dockerfile. 

_Dockerfile.ui:_
```
FROM joxit/docker-registry-ui:2
COPY nginx.conf /etc/nginx/conf.d/default.conf
```

_docker-compose.yml_:
```
version: '2.0'
services:
  registry:
    image: registry:2.7
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry.yml:/etc/docker/registry/config.yml
    networks:
      - registry-ui-net

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - SINGLE_REGISTRY=true
    volumes:
      - ./read-write.htpasswd:/etc/nginx/auth/read-write.htpasswd:ro
      - ./read-only.htpasswd:/etc/nginx/auth/read-only.htpasswd
    depends_on:
      - registry
    networks:
      - registry-ui-net
networks:
  registry-ui-net:
```

Then simply:

* `docker-compose build --pull`
* `docker-compose up -d`
