### ISSUE TITLE
How to run `docker manifest` when use docker-registry-ui?

### ISSUE THREAD

**Issue by devome** [Joxit/docker-registry-ui#250]
## My registry config:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
```

## When docker-registry-ui are not used

docker-compose file:
```
version: "3.7"
services:
  registry:
    image: registry:latest
    restart: always
    container_name: registry
    hostname: registry
    network_mode: bridge
    ports:
      - 5000:5000
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./registry:/var/lib/registry
```
When I run the following command, the output is valid.
```
docker manifest create --insecure "10.0.0.11:5000/image:latest" "10.0.0.11:5000/image:amd64 10.0.0.11:5000/image:arm64 10.0.0.11:5000/image:armv7"
docker manifest push --insecure --purge "10.0.0.11:5000/image:latest"

## output
Created manifest list 10.0.0.11:5000/image:latest
sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

## When docker-registry-ui are used

docker-compose file:
```
version: "3.8"
services:
  registry:
    image: registry:latest
    restart: always
    container_name: registry
    hostname: registry
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - ./registry:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 5000:5000
    container_name: registry_ui
    hostname: registry_ui
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - NGINX_LISTEN_PORT=5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_HEADER_X_Forwarded_For=$$proxy_add_x_forwarded_for
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
```
When I run the following command, the output is error.
```
docker manifest create --insecure "10.0.0.11:5000/image:latest" "10.0.0.11:5000/image:amd64 10.0.0.11:5000/image:arm64 10.0.0.11:5000/image:armv7"
docker manifest push --insecure --purge "10.0.0.11:5000/image:latest"

## output
Created manifest list 10.0.0.11:5000/image:latest
failed to configure transport: unsupported registry version
```

Why does this error occur? How should I modify the configuration file?
