### ISSUE TITLE
nginx: [emerg] no "events" section in configuration

### ISSUE THREAD

**Issue by zctmdc** [Joxit/docker-registry-ui#257]
Hi, I use this docker registry UI and I have an issue...

## Bug description

nginx erro then exit

## How to Reproduce
run command: 'docker-compose up' 
get erro log:
```
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/07/17 02:02:26 [emerg] 1#1: no "events" section in configuration
nginx: [emerg] no "events" section in configuration
```

container exit

For service bug, steps to reproduce the behavior:

My docker-compose file
```yml

services:
    registry:
        privileged: true
        image: registry
        restart: always
        container_name: registry
        ports:
            - 5050:5000
        volumes:
            - ../data/registry:/var/lib/registry
    registry-ui:
        image: joxit/docker-registry-ui
        container_name: registry-ui
        environment:
            - REGISTRY_TITLE=my_registry
            - NGINX_PROXY_PASS_URL=http://registry:5000
            - SINGLE_REGISTRY=true
            - DELETE_IMAGES=true
        restart: always
        ports:
            - 5080:80
        depends_on:
            - registry
        links:
            - registry
```

## System information

- OS:  DSM 918+ 7.0.1-42218

- Docker registry UI:
  - Version: latest
  - Server: docker

  - Docker version: Docker version 20.10.3, build b455053
  - Docker registry ui tag: latest
  - OS/Arch:  linux/amd64
  - Tools: docker-compose

## Additional context

full log:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/90-docker-registry-ui.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/07/17 02:08:50 [emerg] 1#1: no "events" section in configuration
nginx: [emerg] no "events" section in configuration
```

**Comment by Joxit** [comment]
Hi there, thank you for using my project.

I tried your docker-compose file and had no issue... This may be caused by `/docker-entrypoint.d/30-tune-worker-processes.sh` and your OS or VM configuration. 

Can you send me the content of `/etc/nginx/nginx.conf` after a server start ?

**Comment by zctmdc** [comment]
is blank

```
# cat docker-compose.yaml

services:
    registry:
        privileged: true
        image: registry
        restart: always
        container_name: registry
        ports:
            - 5050:5000
        volumes:
            - ../data/registry:/var/lib/registry
    registry-ui:
        image: joxit/docker-registry-ui
        container_name: registry-ui
        environment:
            - REGISTRY_TITLE=registry.dsm.em.zctmdc.cn
            - NGINX_PROXY_PASS_URL=http://registry:5000
            - SINGLE_REGISTRY=true
            - DELETE_IMAGES=true
        ports:
            - 5080:80
        depends_on:
            - registry
        links:
            - registry
        # restart: always

```

1. run `docker-compose up -d --rem`
2. until  *registry-ui* stop
3. run `docker cp  registry-ui:/etc/nginx/nginx.conf tmp.conf`
4. run `ls -l tmp.conf`
```
-rw-r--r-- 1 root root 0 Jan 25 23:26 tmp.conf
```
