### ISSUE TITLE
Support auth ?

### ISSUE THREAD

**Issue by naerion89** [Joxit/docker-registry-ui#26]
Is there any support for docker registry authentication ?

**Comment by Joxit** [comment]
Hello,
`docker-registry-ui` already supports authentication.
Check the [registry configuration example](https://joxit.github.io/docker-registry-ui/#registry-example).
You will need these parts : 
```yml
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['<URL of your docker-registry-ui with port>']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization']
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```
