### ISSUE TITLE
Basic Auth doesn't work

### ISSUE THREAD

**Issue by YFrendo** [Joxit/docker-registry-ui#267]
Hi! 
First thanks for your project it's really awesome.

I have the registry-ui wich work perfectly and I want to put a basic Auth on it
My registry-ui work on kubernetes with this conf:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "docker-ui-deploy"
  namespace: "container-registry"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: registry-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      nodeName: my-node-name
      volumes:
      - name: nginx-env
        hostPath:
          path: /mypath/nginx.env
          type: File
      containers:
      - name: registry-ui
        image: joxit/docker-registry-ui:latest
        volumeMounts:
        - mountPath: /etc/nginx.env
          name: nginx-env
        env:
        - name: REGISTRY_TITLE
          value: "My Registry"
        - name: NGINX_PROXY_PASS_URL
          value: "http://docker-registry:5000" #A service
        - name: SINGLE_REGISRTY
          value: "true"
        - name: DELETE_IMAGES
          value: "true"
```

The nginx.env file : NGINX_PROXY_HEADER_Authorization=Basic mybase64hash

But when I connect to my URL the auth doesn't show did I miss something ?

Thanks you!

**Comment by Joxit** [comment]
Hi, thank you for using my project.

Did you know, there is an official helm chart https://helm.joxit.dev/charts/docker-registry-ui/ ?

If you want Basic Auth, you will need to update your registry server configuration and add authentication options

```
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

The `NGINX_PROXY_HEADER_Authorization` will prevent you from entering credentials when using the interface with your secured registry server
