### ISSUE TITLE
Cannot connect to docker registry secured with self-signed certificate

### ISSUE THREAD

**Issue by jaheilman** [Joxit/docker-registry-ui#268]
I have configured my docker registry to respond on port 443 with a self-signed certificate, no authentication.  The UI is standard http (it could be https, just do not need that)  I (attempted) to configure this appropriately to docker-registry-ui, but when opening the ui wepage I get an error about adding Access-Control-Allow-Origin, and the console log says:

```
registry-ui  | 172.26.0.1 - - [24/Sep/2022:18:49:26 +0000] "GET / HTTP/1.1" 200 1580 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" "-"
registry     | 2022/09/24 18:49:27 http2: server: error reading preface from client 172.26.0.1:46182: remote error: tls: bad certificate
```

I suspect that the UI doesn't trust my self-signed certificate, and I haven't provided it, so it won't connect.  But how to provide the cert to registry-ui?

My docker compose:
```
version: '3.7'
services:
  registry:
    image: registry:2.7
    container_name: registry
    ports:
      - 443:443
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    volumes:
      - ./registry_data:/var/lib/registry
      - ./registry_config/simple.yml:/etc/docker/registry/config.yml
      - ./certs:/certs
  ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - 8000:80
    environment:
      - REGISTRY_TITLE=TestUI
      - REGISTRY_URL=https://localhost
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
```

And registry_config/simple.yml

```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
https:
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

For example, to do docker push localhost:443/someimage from a client, I have to add the cert to /etc/docker/certs.d/localhost:443/ca.crt
For 'curl -v https://localhost/v2` to work I needed to add certs/domain.crt the cert to /usr/local/share/ca-certificates/ca.crt and run update-ca-certificates.
I tried the latter inside the registry-ui container, but it apparently looks in some other location for the cert.
