### ISSUE TITLE
UI can't access registry through docker network

### ISSUE THREAD

**Issue by squid-dev** [Joxit/docker-registry-ui#269]
Hello,
  I'm having trouble getting Registry UI to access the registry through the docker network. I get the banner with the 'Check your connection and your registry must have "Access-Control-Allow-Origin"...' error.

If I change the "REGISTRY_URL" variable in the docker-compose.yml file to the IP address of the docker host, it works.

If I shell into the registry_ui container and run:
`curl --location --request GET 'http://registry:5000/v2/_catalog'`
that works too.

I'm not sure what to try next. Thanks!

docker-compose.yml:
```
version: "3"

services:
  ui:
    container_name: registry_ui
    image: joxit/docker-registry-ui
    restart: always
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Docker Registry
      - SINGLE_REGISTRY=true
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
    networks:
      - registry-net
  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./registry_config.yml:/etc/docker/registry/config.yml
      - ./registry_data:/var/lib/registry
    networks:
      - registry-net

networks:
  registry-net:
    external: true 
```

registry_config.yml:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Accept']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
