### ISSUE TITLE
Your registry must have Access-Control-Allow-Origin header set to XXX

### ISSUE THREAD

**Issue by gamosoft** [Joxit/docker-registry-ui#275]
Hi, I use this docker registry UI and I have an issue...

## Bug description
Using the latest docker hub version (2.3.2) it keeps asking for 'Access-Control-Allow-Origin' header

## How to Reproduce
Just compose up the following configuration file and open up a browser in http://localhost:8980

My docker-compose file
```yml
services:
  registryui:
    image: joxit/docker-registry-ui:2.3.2
    ports:
      - 8980:80
    environment:
      - REGISTRY_TITLE=My Container Registry
      - REGISTRY_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    networks:
      - homelab-network
    restart: unless-stopped
    depends_on:
      registry:
        condition: service_healthy

  registry:
    image: registry:2.8.1
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - homelab-registry-data:/var/lib/registry
      - ./config.yml:/etc/docker/registry/config.yml
    networks:
      - homelab-network
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider --no-check-certificate http://localhost:5000/v2 || exit 1
      interval: 3s
      timeout: 3s
      retries: 10

networks:
  homelab-network:
    name: homelab-network
    driver: bridge

volumes:
  homelab-registry-data:

```

My private docker registry configuration (config.yml)
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  debug:
    addr: :5001
    prometheus:
      enabled: true
      path: /metrics  
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

## Expected behavior

It should work and not display the error message shown in the screenshot below

## Screenshots

![image](https://user-images.githubusercontent.com/9968384/196429656-8f0979c2-553f-475d-8d5a-ee256ccd00a7.png)

## System information

- OS: W10
- Browser:
    - Name:  Opera
- Docker registry UI:
    - Version: 2.3.2

## Additional context

If instead of using version 2.3.2 I switch to version 1.5-static it works fine as shown below:

```yml
services:
  registryui:
    image: joxit/docker-registry-ui:1.5-static
    ports:
      - 8980:80
    environment:
      - REGISTRY_TITLE=My Container Registry
      - REGISTRY_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    networks:
      ....
```

![image](https://user-images.githubusercontent.com/9968384/196430576-4bda08d3-b9a6-415e-bb90-b8ceb246e988.png)

Thanks for your help.
