### ISSUE TITLE
Mixed Content: The page at `https://dockerhub.xxx.org` was loaded over HTTPS, but requested an insecure server endpoint `http://localhost:5000`. This request has been blocked

### ISSUE THREAD

**Issue by Wern-rm** [Joxit/docker-registry-ui#277]
Hello, please tell me how to solve the problem with Access-Control-Allow-Origin.

Here is my configuration:
```
version: '2'

services:
    registry-srv:
        image: registry:2.7
        restart: always
        volumes:
            - /opt/dockerhub/storage:/var/lib/registry
            - /opt/dockerhub/htpasswd:/etc/docker/registry/htpasswd
        ports:
            - 5000:5000
        environment:
            - REGISTRY_HTTP_HEADERS_X-Content-Type-Options=[nosniff]
            - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['https://dockerhub.xxx.org']
            - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=['HEAD', 'GET', 'OPTIONS', 'DELETE']
            - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers=['Authorization']
            - REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers=['Docker-Content-Digest']
            - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=['true']
            - REGISTRY_AUTH_HTPASSWD_REALM=basic-realm
            - REGISTRY_AUTH_HTPASSWD_PATH=/etc/docker/registry/htpasswd
            - REGISTRY_STORAGE_DELETE_ENABLED=true
        networks:
            - registry-ui-net
        container_name: registry-srv
    registry-ui:
        image: joxit/docker-registry-ui:latest
        restart: always
        ports:
            - 9030:80
        environment:
            - REGISTRY_TITLE=Private Docker Registry
            - REGISTRY_URL=http://localhost:5000
            - DELETE_IMAGES=true
            - SINGLE_REGISTRY=true
        container_name: registry-ui

networks:
    registry-ui-net:
```

My domain by which I want to access the UI: https://dockerhub.xxx.org , which works via HTTPS.

My server architecture consists of: A separate Nginx server that proxies server 2 - where docker is installed and where Registry and RegistryUI are deployed.

Configuration of my external Nginx:

```
server {
    listen                                 80;
    server_name                    dockerhub.xxx.org;
    client_max_body_size    9999M;
    listen                                443 ssl;
    ssl_certificate                 /opt/xxx.org.crt;
    ssl_certificate_key         /opt/xxx.org.key;

    location / {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://172.16.20.252:9030;
    }
}
```

Perhaps I understand my problem - I need the Registry itself to also have its own domain, where I will refer to in the UI and it will be 2 different applications, but I still don't fully understand...

Excuse me for my terrible English and thank you for your help!
