### ISSUE TITLE
where to put Access-Control-Allow-Origin header?

### ISSUE THREAD

**Issue by pcace** [Joxit/docker-registry-ui#278]
hi there, i am running your registry ui wich is supposed to use my private registry.
so i am running this: joxit/docker-registry-ui:latest with these environment variables: 
REGISTRY_TITLE=asdfasdf
SIGNLE_REGISTRY=true
REGISTRY_URL=https://dockerregistry.beta.url.com
the registry needs pw/user authentification (via htaccess) it also has in the nginx configuration: 
   ```
            add_header 'Access-Control-Allow-Origin' '*'
            add_header 'Access-Control-Allow-Credentials' 'true'
            add_header 'Access-Control-Allow-Headers' 'Authorization, Accept, Cache-Control'
            add_header 'Access-Control-Allow-Methods' 'HEAD, GET, OPTIONS'
```

i sadly still get the Access-Control-Allow-Origin error: 

![image](https://user-images.githubusercontent.com/1011875/208919321-6be4a03e-ed45-404b-adb7-c1c38533da7d.png)

accessing this in the browser totally works: 
https://dockerregistry.beta.url.com/v2/_catalog?n=100000

what am i doing wrong here? any help would be great!! 
Thanks a lot!

**Comment by sorcerb** [comment]
Hello, Joxit
I have same problem. I create 2 site: registry.site and ui.registry.site
1. If I add: add_header 'Access-Control-Allow-Origin' 'https://registry.site' web show popup error, that need use for CORS ui.registry.site
2. If I add: add_header 'Access-Control-Allow-Origin' 'https://ui.registry.site' I got this:
![Screenshot_4](https://user-images.githubusercontent.com/34737538/209394440-999d1c17-4819-4d77-bacd-7f288ff20447.png)

**Comment by Joxit** [comment]
Hi @sorcerb okay, so this one is in the FAQ

> -   Why OPTIONS (aka preflight requests) and DELETE fails with 401 status code (using Basic Auth) ?
>     -   This is caused by a bug in docker registry, it returns 401 status requests on preflight requests, this breaks [W3C preflight-request specification](https://www.w3.org/TR/cors/#preflight-request). I suggest to have your UI on the same domain than your registry e.g. registry.example.com/ui/ **or** use `NGINX_PROXY_PASS_URL` **or** configure a nginx/apache/haproxy in front of your registry that returns 200 on each OPTIONS requests. (see [#104](https://github.com/Joxit/docker-registry-ui/issues/104), [#204](https://github.com/Joxit/docker-registry-ui/issues/204), [#207](https://github.com/Joxit/docker-registry-ui/issues/207), [#214](https://github.com/Joxit/docker-registry-ui/issues/214), [#266](https://github.com/Joxit/docker-registry-ui/issues/266)).


So your options are : 
1. As I said in the FAQ, use `NGINX_PROXY_PASS_URL`
2. Configure a nginx/apache/haproxy in front of your docker registry server and return 200 on each OPTION requests

**Comment by pcace** [comment]
> Hello, thank you for using my project.
> 
> Please read the documentation about [CORS](https://github.com/Joxit/docker-registry-ui#using-cors)
> 
> > If your docker registry need credentials, you will need to send these HEADERS (you must add the protocol `http`/`https` and the port when not default `80`/`443`):
> 
> That means in your nginx configuration you should use this line instead of `*`
> 
> ```
>          add_header 'Access-Control-Allow-Origin' 'https://dockerregistry.beta.url.com'
> ```

Hi, 

thanks for your reply but i still cannot really figure out how to make it work. 
can i use env variables to achieve this? so that i can run the whole thing directly form docker like so somehow: 

```
image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
    here somehow the line
             add_header 'Access-Control-Allow-Origin' 'https://dockerregistry.beta.url.com'
    as env variable?
    depends_on:
      - registry
    networks:
      - registry-ui-net

```

**Comment by Joxit** [comment]
The line  `add_header 'Access-Control-Allow-Origin' 'https://dockerregistry.beta.url.com'` was inspired from your first post, I was supposing you were configuring your own nginx server ?

As I said last time you should read the [CORS](https://github.com/Joxit/docker-registry-ui#using-cors) section from the doc. If you want to add the access control allow origin, this is a **docker registry server** configuration, or your personal nginx configuration, not a UI one!

If you want to configure your docker registry server, add in your `config.yml `

```yaml
http:
  headers:
    Access-Control-Allow-Origin: ['http://registry.example.com']
    Access-Control-Allow-Credentials: [true]
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS'] # Optional
```
