### ISSUE TITLE
Image deletion confirmation

### ISSUE THREAD

**Issue by mcusgithub** [Joxit/docker-registry-ui#285]
- Issue
  - When DELETE_IMAGES = true, clicking the trash button immediately deletes the selected tag(s) / image(s)
  - The trash icon can be clicked by accident and the operation cannot be undone
  - There should be a confirmation step
- Proposed feature
  - Add a confirmation step (dialog) when deleting one or more tags / images.

**Comment by Joxit** [comment]
Hi, thank you for using my project and posting issues :smile: 

Which version are you using ? I think this features has been done two years ago in 2.0.0 with https://github.com/Joxit/docker-registry-ui/pull/182

**Comment by mcusgithub** [comment]
I'm using the "joxit/docker-registry-ui:1.5-static" Docker image. Based on your comment, I now realize that this image, and actually all ui-static images, are ~ 2 years old!, I think. I'm using this particular image because I couldn't get joxit/docker-registry-ui:latest to work properly; the UI would always report a "server not found error" when the compose / parameters files are correct afaik. I tried all kind of things for a couple of days with no luck. I finally came across a comment (old I imagine) suggesting to use a -static image instead in this case and it worked. This report is irrelevant since it refers to an old version. My current installation is certainly not the best but it's functional. I'd still like to know how I could get a recent image to work but I don't know what could possibly be wrong. Thank you for developing this great project and for your help.

**Comment by Joxit** [comment]
Hi, you can refer to the migration guide linked in the readme https://github.com/Joxit/docker-registry-ui/wiki/Migrating-from-1.x-to-2.x

**Comment by mcusgithub** [comment]
Yes, I tried this and many other things based on the documentation and comments from other users. I recently gave 2.x another tried from scratch but still no luck. I'll just stick to 1.5-static for now since it does the job for me at this time. Thanks again for your project and your help.

**Comment by Joxit** [comment]
Even with my examples you didn't succeed?

Maybe if you share your configuration and error I can troubleshoot your issue?

**Comment by mcusgithub** [comment]
Thanks for following up and offering to help further. No, I couldn't get it to work unfortunately but 1.5 does work for me :-) I'll try to get back to it and share my configuration files when possible.

**Comment by mcusgithub** [comment]
I haven't had the time to experiment further with 2.0, but here is a copy of my 1.5 configuration. It's pretty basic and it works. I'd be interested in knowing how to translate it correctly to 2.0:

** access **
(Note: on a personal private network, no sensitive info stored and just for me = https not needed)
http://192.168.1.23:7000

** docker **
docker-compose -f docker-compose.yml up -d

**docker-compose.yml**
# Note: added this registry to 'insecure registry' list
# See: /etc/docker/daemon.json
# {
#  "insecure-registries" : ["192.168.1.23:7000"]
# }

version: '2.0'
services:
  registry:
    image: registry:2.7
    environment:
# Important : to be able to delete tags
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /home/master/User/docker_registry_ui2/dockerregistry_data:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
##  image: joxit/docker-registry-ui:static # older version
    image: joxit/docker-registry-ui:1.5-static
    ports:
      - 7000:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://registry:5000
      - DELETE_IMAGES=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
**~~~~~~~~**

**Comment by Joxit** [comment]
Your new configuration should be:

```yml
version: '2.0'
services:
  registry:
    image: registry:2.7
    environment:
# Important : to be able to delete tags
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - /home/master/User/docker_registry_ui2/dockerregistry_data:/var/lib/registry
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:2.3.3
    ports:
      - 7000:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - DELETE_IMAGES=true
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
```
