### ISSUE TITLE
Trouble freeing up space after garbage collection

### ISSUE THREAD

**Issue by arp-mbender** [Joxit/docker-registry-ui#289]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I'm using a simple "ui-with-proxy" setup based on the provided examples (no passwords, it's only for internal use). The only modification added was changing the configuration to enable deletions. While I am able to press the delete button on the UI and I'm able to run the garbage collection process, it appears nothing is getting removed from the registry volume. Alas, my experience with the registry has only just begun, so I'm unsure if this is an issue with the configuration, registry itself or somehow created by the web UI.

## How to Reproduce

For service bug, steps to reproduce the behavior:

My docker-compose file
```yml
version: '2.0'
services:
  registry-adm:
    image: registry:2.7
    restart: unless-stopped
    expose:
      - 5000
    volumes:
      - registry-data:/var/lib/registry
      - ./registry-config/adm.yml:/etc/docker/registry/config.yml

  ui-adm:
    image: joxit/docker-registry-ui:latest
    restart: unless-stopped
    ports:
      - 5001:80
    environment:
      - REGISTRY_TITLE=Docker ADMIN
      - NGINX_PROXY_PASS_URL=http://registry-adm:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry-adm

volumes:
  registry-data:
```

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']

```

Using that setup I was able to push some custom images to the registry, and later used the UI to remove some images. At the end of everything I use `docker exec myregistrycontainername registry garbage-collect --delete-untagged  /etc/docker/registry/config.yml
` to run the garbage collection.

## Expected behavior

Perhaps I'm missing something, but I'd expect the garbage collection to collect old images and remove them, freeing up space?

## System information

- OS: Ubuntu Server 
- Docker registry UI:
    - Version: [e.g. 1.4.0]
    - Server: docker
    - Docker version: 23.0.0
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: docker-compose
