### ISSUE TITLE
How do I deploy this using k3s and traefik? Can you pl provide an example?

### ISSUE THREAD

**Issue by santoshv98** [Joxit/docker-registry-ui#290]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kubal5003** [comment]
It should be something similar to this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: 'Your title'
            - name: REGISTRY_URL
              value: 'https://your-registry-url-goes-here'
            - name: SINGLE_REGISTRY
              value: 'true'
            - name: DELETE_IMAGES
              value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: registry
spec:
  selector:
    app: registry-ui
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: registry
spec:
  stripPrefix:
    prefixes:
      - /ui

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ui
  namespace: registry
  labels:
    app: registry-ui
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: registry-stripprefix@kubernetescrd

spec:
  tls:
    - hosts:
        - your.host.goes.here
      secretName: registry-tls-secret
  rules:
    - host: your.host.goes.here
      http:
        paths:
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: docker-registry-ui
                port:
                  number: 80

```
However I haven't figured out yet how to make the UI work correctly under a path `/ui` so this is not a fully working example unfortunately.
