### ISSUE TITLE
Docker Registry UI 2.4.1 does not display date, image name and history when connecting to an external registry.

### ISSUE THREAD

**Issue by amaczuga** [Joxit/docker-registry-ui#292]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I'm connecting docker-registry-ui to an external registry (the UI is not hosted together with the registry).
The result - no date, image name and history.

Thanks in advance for helping me understand my misconfiguration.

## How to Reproduce

For UI bug, steps to reproduce the behavior:
1. Go to main page of docker-registry-ui
2. Click on repository name to display tags
3. See the tag list with no names and dates
4. Click history icon
5. See the spinner spin and nothing more happens

For service bug, steps to reproduce the behavior:
My docker run command
```bash
docker run --rm -p 80:80 -d --name regui -e 'SHOW_CATALOG_NB_TAGS=true' -e NGINX_PROXY_PASS_URL='https://registry.redacted.com' -e 'DEFAULT_REGISTRIES=https://registry.redacted.com' -e 'SHOW_CONTENT_DIGEST=true' joxit/docker-registry-ui:2.4.1
```

My private docker registry configuration (helm chart twuni/docker-registry 1.16.0)
```yml
---
deploymentStrategy: Recreate
image:
  tag: 2.8.1
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,Accept"
    nginx.ingress.kubernetes.io/cors-expose-headers: "*, Docker-Content-Digest"
  hosts:
    - registry.redacted.com
  tls:
    - hosts:
        - registry.redacted.com
s3:
  bucket: "docker-registry"
  region: "us-west-1"
  regionEndpoint: "redacted"
  rootdirectory: "/private"
  secrets:
    s3:
      accessKey: "redacted"
      secretKey: "redacted"
  storage: "s3"
```
What I found so far is when I use curl and don't set `Accept: application/vnd.docker.distribution.manifest.v2+json, ...` header, then I get a rich, `schemaVersion: 1` response with logs of data. When I do set the header (as docker-registry-ui does), then I am getting only something like this (also, this is the response UI is getting, as I inspect the browser internals):

```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 2923,
      "digest": "sha256:50518c142df436ba1d602a8712c031f63e394900f7f2171f7d62c53470c2b25e"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 72165530,
         "digest": "sha256:17385548ba54dd00b2b73dc106749019fcc0cc5641317c97766f14647d06ad6e"
      },
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 65135462,
         "digest": "sha256:cc8c92c0296bbc71f436b31f375f457f900a1719db5a1eb78c3b74e843a8855d"
      }
   ]
}
```

Also, the js console throws these errors:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'digest')
    at e.value (docker-registry-ui.js:40:38918)
    at XMLHttpRequest.<anonymous> (docker-registry-ui.js:40:52722)
    at XMLHttpRequest.<anonymous> (docker-registry-ui.js:40:39316)
```

## Expected behavior

I would like the image names and dates listed, also history/Dockerfile view to work in my environment.

## Screenshots

The outcome looks identical to this one:
![](https://user-images.githubusercontent.com/1045063/117471669-67e55e00-af58-11eb-90fd-72d38642bf58.jpg "")

## System information

- OS: Fedora 31
- Browser:
    - Name:  Chrome
    - Version: 109.0.5414.120 64-bit
- Docker registry UI:
    - Version: 2.4.1
    - Server: docker daemon
    - Docker version: 20.10.3
    - Docker registry ui tag: 2.4.1
    - OS/Arch: linux/amd64
    - Tools: docker
