### ISSUE TITLE
Allow to pass headers via env variables

### ISSUE THREAD

**Issue by muzammil786** [Joxit/docker-registry-ui#305]
I am running the registry UI via podman/docker directly and not as a docker-compose file.

`sudo podman run -d -p 8085:80 --env NGINX_PROXY_PASS_URL="http://$(sudo podman inspect registry -f '{{ .NetworkSettings.IPAddress }}'):5000" --env SINGLE_REGISTRY=true --env DELETE_IMAGES=true --name docker-registry-ui docker-registry.repo.ukdn.thalesuk/joxit/docker-registry-ui:latest`

I am getting error on image deletion 

`{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]} `

I guess this is because the headers are not passed properly to NGINX as specified in the readme:

```
http:
  headers:
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

How can I pass those headers via environment variables?
