### ISSUE TITLE
Multiarch image creation date and history

### ISSUE THREAD

**Issue by nevergone** [Joxit/docker-registry-ui#308]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I build a multiarch Docker image with folowing command:
`docker buildx build --platform linux/amd64,linux/arm/v6,linux/arm/v7 --output=type=image,push=true,registry.insecure=false -t nevergone/test-latest`

But image creation date and image history is not available (see attached screenshot). What do I do wrong? The images are created (I tried it) and I can also upload them to Docker Hub.
Thanks!

For service bug, steps to reproduce the behavior:
My docker-compose file
```
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      DEBUG: true
      REGISTRY_STORAGE_DELETE_ENABLED: true
      REGISTRY_CATALOG_MAXENTRIES: 100000
    volumes:
      - ./registry-config/simple.yml:/etc/docker/registry/config.yml
      - ./registry:/var/lib/registry/
  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 8082:80
    environment:
      REGISTRY_TITLE: Private Docker Registry
      REGISTRY_URL: http://127.0.0.1:5000
      USE_CONTROL_CACHE_HEADER: true
      SINGLE_REGISTRY: true
      DELETE_IMAGES: true
    depends_on:
      - registry
    profiles:
      - ui
```

My private docker registry configuration
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
```

## Screenshots

![Screenshot_20230515-091342](https://github.com/Joxit/docker-registry-ui/assets/240642/954c3254-d45f-46e2-a2ff-41d1e75570d6)

## System information

- OS: Ubuntu Linux 22.04
- Browser:
    - Name:  Firefox
    - Version: 113
- Docker registry UI:
    - Version: 2.4.1
    - Server: Docker
    - Docker version: 23.0.6
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: Docker compose
