### ISSUE TITLE
Buildx multiarch image date and history not shown

### ISSUE THREAD

**Issue by GoryMoon** [Joxit/docker-registry-ui#309]
Hi, I use this docker registry UI and I have an issue...

## Bug description

Moved from the comment in https://github.com/Joxit/docker-registry-ui/issues/308#issuecomment-1549366336 to it's own issue.

Buildx added `provenance` as default in [v0.10](https://github.com/docker/buildx/releases/tag/v0.10.0), this changed it to use `OCI` tags to be compliant.
To be able to show history you need to disable this by adding `--provenance=false` to the build command.

I build my images more or less like this:
```sh
docker buildx build --platform linux/amd64,linux/arm64 --tag <image name> --output=type=registry .
```

I don't see how the registry UI couldn't support this for multiarch builds as when looking at the API response it's very similar to how the docker manifest is.
This is what is returned with the manifest from a tag.
> E.g. `/v2/<image name>/manifests/latest`:
<details>
<summary>Click to expand tag manifest </summary>

```json
{
    "mediaType": "application/vnd.oci.image.index.v1+json",
    "schemaVersion": 2,
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:9f38533c3ac11fe5b6d9c08aa5f683887159ecbc01ee65635b2fb3ab6de57ab0",
            "size": 2761,
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:caac61937ce912af68dd7b09ea16be9e15211f7319d800913d19a80b73b4a298",
            "size": 2761,
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:d388def5035290ee739d973cc9e8549e237f423de26dee55ea4949a40d01da65",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:9f38533c3ac11fe5b6d9c08aa5f683887159ecbc01ee65635b2fb3ab6de57ab0",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        },
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "digest": "sha256:6f5e15228ac5ad5dacfbbfc97df6564a9ab1cd0adcdb197b00a627cbe3b7cc51",
            "size": 566,
            "annotations": {
                "vnd.docker.reference.digest": "sha256:caac61937ce912af68dd7b09ea16be9e15211f7319d800913d19a80b73b4a298",
                "vnd.docker.reference.type": "attestation-manifest"
            },
            "platform": {
                "architecture": "unknown",
                "os": "unknown"
            }
        }
    ]
}
```

</details>

You can use the digest of the previous manifest like when you are using `application/vnd.docker.distribution.manifest.list.v2+json` to get the actual image here:

https://github.com/Joxit/docker-registry-ui/blob/bc80050a4488b94cafe0595f7969dff13070c0c2/src/scripts/docker-image.js#L102-L111

Should probably only do this if the response from the tag manifest response is of the `application/vnd.oci.image.manifest.v1+json` type.

When using the digest from the first manifest this is what's returned.
And using that `config` blob returns the history as the current system expects.
> E.g. `/v2/<image name>/manifests/sha256:9f38533c3ac11fe5b6d9c08aa5f683887159ecbc01ee65635b2fb3ab6de57ab0`:
<details>
<summary>Click to expand digest manifest</summary>

```json
{
    "mediaType": "application/vnd.oci.image.manifest.v1+json",
    "schemaVersion": 2,
    "config": {
        "mediaType": "application/vnd.oci.image.config.v1+json",
        "digest": "sha256:8f2e7c70dac05c95bd5a522cf4a059857fc8c997ad1cdf9e2b3eff9a37fe9c4c",
        "size": 9253
    },
    "layers": [
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:1efc276f4ff952c055dea726cfc96ec6a4fdb8b62d9eed816bd2b788f2860ad7",
            "size": 31366757
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:a2f2f93da48276873890ac821b3c991d53a7e864791aaf82c39b7863c908b93b",
            "size": 1582262
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:12cca292b13cb58fadde25af113ddc4ac3b0c5e39ab3f1290a6ba62ec8237afd",
            "size": 212
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:d73cf48caaac2e45ad76a2a9eb3b311d0e4eb1d804e3d2b9cf075a1fa31e6f92",
            "size": 46042445
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:e832be86182094add78a1690b0fbd8818e40710a53d43171db4b271d43d46158",
            "size": 5484
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:871f7cebf585d387fde9f3fd270668065701606577a1008ed3b3acfac8274cc4",
            "size": 18460921
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:207983e6a84c88158ffa317f4341aa449fe063b44834682569d7b2506c9f2437",
            "size": 859851653
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:1d99b33ce83abb0fd774713bf9dd14c29710d54f969b57056a35f5a9b332054e",
            "size": 179
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:ca5cba012caf700f0fb5ddb9a7904eae14744e4ab44594c1b482ecbad77f8d1b",
            "size": 3057
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:39a7c4fc07c05d4870b4d95a7a0015ab56c4e07e516cf549a54bf3e9fd8ff73a",
            "size": 212
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:401b2e2746eb54009b1f49b321161cfc251c1c8d12444b0eeb463a9b4f1902ea",
            "size": 329
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:4eafb804449bab1cdde11fb488b0a7a1f59f89bf24a530463a1cb91c07eecf8a",
            "size": 5323
        },
        {
            "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
            "digest": "sha256:0f7e12b417c3dbebe0a2ba16556075c1b64823b25ba115c43ec14f494d6c64b4",
            "size": 390
        }
    ]
}
```

</details>

#### For service bug, steps to reproduce the behavior:
My docker-compose file
```yml
version: '3'

services:
  registry:
    container_name: registry
    image: registry:2
    volumes:
      - ./registry/data:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      - REGISTRY_HTTP_SECRET=<secret>
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.registry.entrypoints: https
      traefik.http.routers.registry.rule: Host(`registry.example.com`)
      traefik.http.services.registry.loadbalancer.server.port: 5000
    networks:
      - traefik-proxy

  registry-ui:
    container_name: registry-ui
    image: joxit/docker-registry-ui:latest
    environment:
      - REGISTRY_TITLE=Registry Repo
      - REGISTRY_URL=https://registry.example.com
      - SHOW_CONTENT_DIGEST=true
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - CATALOG_ELEMENTS_LIMIT=1000
    restart: unless-stopped
    depends_on:
      - registry
    labels:
      traefik.enable: true
      traefik.http.routers.registry-ui.entrypoints: https
      traefik.http.routers.registry-ui.rule: Host(`registry-ui.example.com`)
      traefik.http.services.registry-ui.loadbalancer.server.port: 80
    networks:
      - traefik-proxy
```

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Max-Age: [1728000]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']

```

## Expected behavior

To be able to view history on multiarch OCI images.

## System information

- OS: Debian 11
- Docker registry UI:
    - Version: 2.4.1
    - Server: docker
    - Docker version: 23.0.5
    - Docker registry version: 2.8.2
    - Docker registry ui tag: latest
    - OS/Arch: linux/arm64
    - Tools: docker-compose
