### ISSUE TITLE
Pagination number invalid 

### ISSUE THREAD

**Issue by dotNetCory** [Joxit/docker-registry-ui#311]
Hi, I use this docker registry UI and I have an issue...

## Bug description

When loading up the page I get the following error, and none of my containers show on the page

{"errors":[{"code":"PAGINATION_NUMBER_INVALID","message":"invalid number of results requested","detail":{"n":100000}}]}

## How to Reproduce

Just loading up the page

## Expected behavior

For it to display the containers in my registry 

## Screenshots

<img width="1058" alt="image" src="https://github.com/Joxit/docker-registry-ui/assets/60733518/0433ce2f-d822-4995-93d0-36e1c1f2fca3">

## System information

- OS: ubuntu 23.04

- Browser:
    - Name:  Chrome (113.0.5672.126) & Safari 16.3 (18614.4.6.1.5)
- Docker registry UI:
    - Version: docker-registry-ui:latest@sha256:32f861051855ea3f923fe2803b87d83b80c6b00d2c82bd4f7f9a1752ccbc5e62
    - Server: docker

    - Docker version: 24.0.1 build 6802122
    - Docker registry ui tag: latest
    - OS/Arch: linux/aarch64
    - Tools: docker stack deploy

## Additional context

Not sure of what to add. I had it all working for a while. 2 things have changed since I last went on, 1 I upgraded to 23.04, and I noticed it as I was swapping my domain name over, using NGINX as ingress. 

NIGINX CONFIG

```
server {
    server_name reg.[ommited for privacy].com;
    listen 80;
    listen 443 ssl;
    
    location /v2 {
        # Do not allow connections from docker 1.5 and earlier
        # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
        if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
        return 404;
        }

        set $upstream reg_registry;
        resolver 127.0.0.11 valid=30s;

        proxy_pass                          https://$upstream:5000;
        proxy_set_header  Host              $http_host;   # required for docker client's sake
        proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_read_timeout                  900;
    }

    location / {
        set $upstream2 reg_ui;
        resolver 127.0.0.11 valid=30s;

        proxy_pass http://$upstream2;
        proxy_set_header  Host              $http_host;   # required for docker client's sake
        proxy_set_header  X-Real-IP         $remote_addr; # pass on real client's IP
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
    }
}

```
Registry compose.yml

```
version: '3'
services:
  registry:
    image: registry:latest
    ports:
      - "5000:5000"
    networks:
      - isaacnet
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      #REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "*"
    volumes:
      - ./auth:/auth
      - ./data:/data
      - /etc/letsencrypt/live/[omitted].com/fullchain.pem:/certs/fullchain.pem
      - /etc/letsencrypt/live/[omitted].com/privkey.pem:/certs/privkey.pem
    restart: always
networks:
  isaacnet:
    external: true
```

UI compose.yml

```
version: "3.9"
services:
  ui:
    image: joxit/docker-registry-ui:latest
    container_name: isaac-reg-ui
    environment:
      - REGISTRY_TITLE= [omitted] Docker Registry
      - NGINX_PROXY_PASS_URL=http://reg_registry:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    networks:
      - isaacnet
networks:
  isaacnet:
    external: true
```
