### ISSUE TITLE
 Docker Registry UI shows 0 images in 0 repositories even if I have repositories defined.

### ISSUE THREAD

**Issue by ghevge** [Joxit/docker-registry-ui#322]
Hi,
Im trying to setup docker-registry-ui using the instruction available in the readme, the registry server and the registry-ui containers are starting OK, I am able to push images into the docker-registry using command line, the registry-ui console is opening but is not showing any repositories.
```
Repositories of Docker Registry UI
0 images in 0 repositories
```

looking at the containers logs I can see the "/v2/_catalog?n=1000" request hitting the docker-registry server, 

```
registry-ui        | 172.20.0.1 - - [03/Jul/2023:15:15:39 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
registry-server    | time="2023-07-03T15:15:40.055359546Z" level=info msg="response completed" go.version=go1.19.9 http.request.host="localhost:81" http.request.id=3306464b-d91e-4cb7-96dc-fbdd9fca124d http.request.method=GET http.request.referer="http://localhost:81/" http.request.remoteaddr="172.20.0.2:47042" http.request.uri="/v2/_catalog?n=1000" http.request.useragent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" http.response.contenttype="application/json; charset=utf-8" http.response.duration="923.228µs" http.response.status=200 http.response.written=20 
registry-ui        | 172.20.0.1 - - [03/Jul/2023:15:15:40 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "http://localhost:81/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
registry-server    | 172.20.0.2 - - [03/Jul/2023:15:15:40 +0000] "GET /v2/_catalog?n=1000 HTTP/1.1" 200 20 "http://localhost:81/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
```

but at the UI level the response to http://localhost:81/v2/_catalog?n=1000 is :

`{"repositories":[]}`

If I call directly the docker-registry api at: http://localhost:5000/v2/_catalog?n=1000, i get this

`{"repositories":["my-ubuntu"]}`

My docker-compose.yml looks like this:

```
version: '3.8'
services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 81:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui

  registry-server:
    image: registry:2.8.2
    restart: always
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Origin: '[''*'']'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
    volumes:
      - /data/dockereg:/var/lib/registry
    container_name: registry-server
```

Any idea what is going on?
