### ISSUE TITLE
[CORS] The `Access-Control-Allow-Credentials` header in the response is missing error is shown but the browser network tab show that it's there and is set to true.

### ISSUE THREAD

**Issue by AJWavio** [Joxit/docker-registry-ui#328]
Hi, I use this docker registry UI and I have an issue...

## Bug description
Error message "The `Access-Control-Allow-Credentials` header in the response is missing and must be set to `true` when the request's credentials mode is on. Origin `https://registry.my-domain.com` is therefore not allowed access." is shown but the browser network tab shows that it's there and is set to true. 

The request/response header is in the screenshots below.

## How to Reproduce

1. Open the UI.
2. Input the registry credentials.
3. After input the credential, the error message is shown.

My docker-compose file
```yml
version: '3.8'

services:
  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    container_name: registry-ui
    ports:
      - 30691:80
    environment:
      - REGISTRY_URL=https://registry.my-domain.com
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
      - THEME=dark

networks:
  default:
    external: true
    name: nginx-proxy-network
```

My private docker registry configuration
```yml
version: '3'

services:
  registry:
    container_name: registry
    restart: always
    image: registry:2
    ports:
      - 36969:36969
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:36969
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/cert1.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey1.pem
      REGISTRY_HTTP_HEADERS_Access-Control-Origin: '[https://registry-ui.my-domain.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /home/docker-composes/registry/data:/var/lib/registry
      - /home/docker-composes/nginx-proxy-manager/letsencrypt/archive/npm-8:/certs
      - /home/docker-composes/registry/auth:/auth

networks:
  default:
    external: true
    name: nginx-proxy-network
```

## Expected behavior

Different error message should be shown if something went wrong because the 'Access-Control-Allow-Credentials' response header is present and is set to true.

## Screenshots

![image](https://github.com/Joxit/docker-registry-ui/assets/137434904/40ebc9f2-3df2-4034-b65d-df0c4c5faa93)
![image](https://github.com/Joxit/docker-registry-ui/assets/137434904/d44966de-d4d5-4110-9398-06126a1fd918)

## System information

- OS: [e.g. Debian, Windows, Mac OS, Android 9...]
- Browser:
    - Name: Microsoft Edge
    - Version: 115.0.1901.183 x64
- Docker registry UI:
    - Server: [docker or dist]
    - Docker version: 24.0.4
    - Docker registry ui tag: main
    - OS/Arch: ubuntu
    - Tools: docker-compose, Ngnix Proxy Manager

## Additional context

I'm using Nginx Proxy Manager as a reverse proxy.
The registry and the ui are hosted on the same domain.

These are Nginx config that I got from Nginx Proxy Manager directory.
Registry Nginx config
```nginx
server {
  set $forward_scheme https;
  set $server         "registry";
  set $port           36969;

  listen 80;
  listen [::]:80;
  
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name registry.my-domain.com;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-8/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-8/privkey.pem;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000; preload" always;

  # Force SSL
  include conf.d/include/force-ssl.conf;

  access_log /data/logs/proxy-host-10_access.log proxy;
  error_log /data/logs/proxy-host-10_error.log warn;

  location / {
    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; preload" always;

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
```

Registry UI Nginx config
```nginx
server {
  set $forward_scheme http;
  set $server        "registry-ui";
  set $port           30691;

  listen 80;
  listen [::]:80;

  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name registry-ui.my-domain.com;

  # Let's Encrypt SSL
  include conf.d/include/letsencrypt-acme-challenge.conf;
  include conf.d/include/ssl-ciphers.conf;
  ssl_certificate /etc/letsencrypt/live/npm-9/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/npm-9/privkey.pem;

  # Asset Caching
  include conf.d/include/assets.conf;

  # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
  add_header Strict-Transport-Security "max-age=63072000; preload" always;

  # Force SSL
  include conf.d/include/force-ssl.conf;

  access_log /data/logs/proxy-host-11_access.log proxy;
  error_log /data/logs/proxy-host-11_error.log warn;

  location / {
    # HSTS (ngx_http_headers_module is required) (63072000 seconds = 2 years)
    add_header Strict-Transport-Security "max-age=63072000; preload" always;

    # Proxy!
    include conf.d/include/proxy.conf;
  }

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}


```
