### ISSUE TITLE
Can't connect to registry

### ISSUE THREAD

**Issue by bielu000** [Joxit/docker-registry-ui#33]
I try to use docker-registry-ui on my localhost.
I use the following docker-compose file(for docker-registry-ui)

```
`version: '3'
services:
  registry-ui:
    image: joxit/docker-registry-ui
    ports:
      - "80:80"
    networks:
      - registry-network

networks:
  registry-network:
    external:
      name: registry-ui-net`
```

and the following for docker-registry:
```
`version: '3'
services:
  registry:
    restart: always
    image: registry:2
    ports:
       - "5000:5000"
    environment:
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      #- /path/data:/var/lib/registry
      #- /path/certs:/certs
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml
    networks:
      - registry-network

networks:
  registry-network:
    external:
      name: registry-ui-net`
```

The problem is that I can't connect by ui container to my registry. It returns 404 http error code. 
But If I will come to the address: http://127.0.0.1:5000/v2/_catalog (which is address of my registry), it returs json array with my repository, which I pushed earlier. 

So why docker container ui cant connect itself to my registry?
The are both in the same network, too.

**Comment by Joxit** [comment]
Hello,
Do you use docker-registry-ui for a single regitry?
If so, I suggest you use the static tag with these parameters so that they can communicate through your network:
```yml
version: '3'
services:
  registry-ui:
    image: joxit/docker-registry-ui:static
    environment:
    - REGISTRY_URL: 'http://registry:5000'
    - REGISTRY_TITLE: 'Choose a title'
    ports:
      - "80:80"
    networks:
      - registry-network

networks:
  registry-network:
    external:
      name: registry-ui-net
```
If you want more informations on `joxit/docker-registry-ui:static` [click here](https://joxit.github.io/docker-registry-ui/#run-the-static-docker).
This version will prevent you from opening port 5000 and your registry will be reachable on port 80.

If you use the interface for several registries, you must go on the interface and add your URLs (with the menu, the 3 points at the top right)
