### ISSUE TITLE
Auth form is not showing

### ISSUE THREAD

**Issue by lorrod** [Joxit/docker-registry-ui#330]
Hi, I use this docker registry UI and I have an issue when configured it with option secured option (REGISTRY_SECURED=true)

My registry is secured by gitlab auth mechanism.

## Bug description

My private docker registry and registry-ui configuration
```yml
  registry:
    restart: always
    image: registry:2.7
    container_name: gitlab_registry
    volumes:
     - ./gitlab/shared/registry:/registry
     - ./certs:/certs
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry-https.rule=Host(`my-external-registry-host.com`)
      - traefik.http.routers.registry-https.entrypoints=websecure
      - traefik.http.routers.registry-https.tls=true
      - traefik.http.routers.registry-https.tls.certresolver=cfdns
      - traefik.http.routers.registry-https.service=registry
      - traefik.http.services.registry.loadbalancer.server.port=5000
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_HEADERS_Access-Control-Origin: '[https://my-external-url.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_AUTH_TOKEN_REALM: https://my-git-url/jwt/auth
      REGISTRY_AUTH_TOKEN_SERVICE: container_registry
      REGISTRY_AUTH_TOKEN_ISSUER: omnibus-gitlab-issuer
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry-ui.rule=Host(``)
      - traefik.http.routers.registry-ui.entrypoints=websecure
      - traefik.http.routers.registry-ui.tls=true
      - traefik.http.routers.registry-ui.tls.certresolver=cfdns
      - traefik.http.routers.registry-ui.service=registry-ui
      - traefik.http.services.registry-ui.loadbalancer.server.port=80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
```

Thank you for your project!
