### ISSUE TITLE
Pagination not working properly

### ISSUE THREAD

**Issue by aneumyvakin-aparavi** [Joxit/docker-registry-ui#338]
Hi, I use this docker registry UI and I have an issue...
v2.5.3
## Bug description
Pagination not working properly

## How to Reproduce
For UI bug, steps to reproduce the behavior:
1. Set `TAGLIST_PAGE_SIZE=20`
2. Click on pagination page 3 etc...
3. See error

## Expected behavior
Pagination page properly open

## Screenshots
![image](https://github.com/Joxit/docker-registry-ui/assets/110675817/7a6248dc-4ff3-488d-94dd-5cc827db1320)

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues.

Can you give me more information, I saw nothing wrong in the UI with your screenshot, and the console do not give mor intel.

Which version are you using?
What's happening when you click on different page?
Which kind of images are you using?

**Comment by aneumyvakin-aparavi** [comment]
Hi, Joxit. Thx for this project.
Which version are you using? 2.5.3 and 2.5.4 this issue too.
What's happening when you click on different page? the page does not open.
Which kind of images are you using? the usual docker images created by the docker builder, or what did you mean?

**Comment by Joxit** [comment]
So, your screenshot is displaying page two but you have the images from the page 1 right ?

Your images in the repository `app-docker-nonprod/app` are amd64 images only ? Multi arch images ?
What is your docker registry UI full configuration ?
Is the page updated when you refresh ? (it uses un query param `page=`)

I cannot reproduce your issue, I have a test repository with 3002 images and its working even if I set `TAGLIST_PAGE_SIZE=20`, that's why I need more information
![image](https://github.com/Joxit/docker-registry-ui/assets/5153882/f0661ea6-6392-4ad5-af54-e2866de70acd)

**Comment by aneumyvakin-aparavi** [comment]
![image](https://github.com/Joxit/docker-registry-ui/assets/110675817/13746694-8888-411b-aa0f-42865e2835cd)

1. Yes i can open 1, 2 pages
2. Yes all images amd64
3. I don't use docker compose, i use hashicorp nomad but the configurations are similar:
```
env {
  SINGLE_REGISTRY        = "true"
  REGISTRY_TITLE         = "APARAVI Registry"
  DELETE_IMAGES          = "true"
  SHOW_CONTENT_DIGEST    = "false"
  SHOW_CATALOG_NB_TAGS   = "true"
  CATALOG_MIN_BRANCHES   = "1"
  CATALOG_MAX_BRANCHES   = "1"
  TAGLIST_PAGE_SIZE      = "20"
  REGISTRY_SECURED       = "false"
  CATALOG_ELEMENTS_LIMIT = "1000"
  PULL_URL               = "docker-registry.blablabla.com"
}
```
4. I can only switch to the 3rd page, but not further... changing the address line page=3 (page=4 it doesn't work anymore)

**Comment by cyberm8** [comment]
Hello, I think I meet a very similar issue.

![image](https://github.com/Joxit/docker-registry-ui/assets/117109145/799c307b-b368-4ec5-b688-9b094602cf34)

When I click on page 2, I get the following error in the console.
UI remains on page 1.

![image](https://github.com/Joxit/docker-registry-ui/assets/117109145/88760396-2ddf-4331-8a7b-6db1adb9a195)

I use docker-compose with the following docker-compose.yml file.

```
---
version: '3.6'

services:
  docker_registry: ...

  docker_registry_ui:
    container_name: docker-registry-ui
    image: joxit/docker-registry-ui:2.5.2-debian
    ports:
      - 127.0.0.1:8080:80 # nginx as reverse proxy
    environment:
      - REGISTRY_TITLE=Foo
      - REGISTRY_URL=https://docker-registry.foo.fr
      - PULL_URL=docker-registry.foo.fr
      - DELETE_IMAGES=false
      - SINGLE_REGISTRY=true
      - HISTORY_CUSTOM_LABELS=true
      - TAGLIST_PAGE_SIZE=20
    depends_on:
      - docker_registry
```

Should I open a dedicated issue ?
