### ISSUE TITLE
Always get CORS error when enabling credentials

### ISSUE THREAD

**Issue by FaisalBudiono** [Joxit/docker-registry-ui#340]
## Bug description
I always get CORS error when enabling credentials. My work around is to disable the credential whenever I want to do a cleanup, but it will mess with the pipeline (Since I need to restart my registry).

I tested my registry config with `docker login` and it works fine.

## How to Reproduce
For UI bug, steps to reproduce the behavior:
1. Click Image
2. See tag list
3. Tag list is missing information and we can see CORS error

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
    readonly:
      enabled: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['https://ui-url.example.com']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
    Access-Control-Allow-Credentials: [true]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/.password
```

```env
REGISTRY_TITLE=Docker Registry 
REGISTRY_URL=https://reg.example.com
SINGLE_REGISTRY=true
SHOW_CONTENT_DIGEST=true
DELETE_IMAGES=true
REGISTRY_SECURED=true
NGINX_PROXY_PASS_URL=http://srv-captain--docker-registry:5000
```
I did try this with and without `NGINX_PROXY_PASS_URL`

## Expected behavior

Should be able to see the detail and delete the image.

## Screenshots

![image](https://github.com/Joxit/docker-registry-ui/assets/48643636/313d7636-f227-421d-ac7c-770612281a3e)

## System information

- OS: [Ubuntu 20.02]
- Browser:
    - Name: [Chrome:117.0.5938.152, Brave:1.59.117]
- Docker registry UI:
    - Server: [docker]
    - Docker version: [Docker version 20.10.22, build 3a2c30b]
    - Docker registry ui tag: [latest, 2.5.4]
    - Tools: [caprover]
