### ISSUE TITLE
CATALOG_NOT_FOUND

### ISSUE THREAD

**Issue by fred-gb** [Joxit/docker-registry-ui#342]
Bonjour 👋🏻 

Orchestrator: Nomad/Consul/Vault
registry: 2.8.3
registry ui: 2.5.6

I try to moved my private registry from VPS to another VPS.

My Nomad job works, but when I reach web UI, I get: 
```
404
CATALOG_NOT_FOUND

We received a 404 status code from your registry.

The contact point was [myprivateregistry.domain.com/v2/_catalog?n=1000](https://myprivateregistry.domain.com/myprivateregistry.domain.com//v2/_catalog?n=1000)
```

config.yml:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://localhost']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
```

env from docker-registry-ui:
```
SINGLE_REGISTRY=true

REGISTRY_URL=myprivateregistry.domain.com

REGISTRY_TITLE=Registry

DELETE_IMAGES=true

SHOW_CONTENT_DIGEST=true

NGINX_PROXY_PASS_URL=http://127.0.0.1:5000

NGINX_PROXY_HEADER_Authorization=Basic BLABLABLABLABLA

NGINX_PROXY_HEADER_X_Forwarded_For=$proxy_add_x_forwarded_for

CATALOG_ELEMENTS_LIMIT=1000

SHOW_CATALOG_NB_TAGS= false

THEME=auto

TAGLIST_ORDER=alpha-asc;num-desc

CATALOG_DEFAULT_EXPANDED=false

CATALOG_MIN_BRANCHES=1

CATALOG_MAX_BRANCHES=1

TAGLIST_PAGE_SIZE=100

REGISTRY_SECURED=true
```

When I `docker exec` from docker-registry-ui container:
`curl -i -H "Authorization: Basic BLABLABLABLABLA" https://myprivateregistry.domain.com/
v2/_catalog`

I get list of images.

`curl -i -H "Authorization: Basic BLABLABLABLABLA" http://127.0.0.1:5000/v2/_catalog`

I get list of images too.

`/usr/share/nginx/html # netstat -lpn`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:30789           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.2:19002         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.2:19001         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1/nginx: master pro
tcp        0      0 0.0.0.0:24609           0.0.0.0:*               LISTEN      -
```
On my old, VPS, works fine, same orchestrator. I just need to moved it for more space and rework the environments vars with docker-registry-ui update.

I add, I can `docker login` I can publish new images on my new registry location.

What I can do?
Thanks
