### ISSUE TITLE
Multi-level min branching ignored?

### ISSUE THREAD

**Issue by u1735067** [Joxit/docker-registry-ui#343]
## Bug description

Hi,
I'm unable to reproduce the `CATALOG_MIN_BRANCHES=1` + `CATALOG_MAX_BRANCHES=2` case described in https://github.com/Joxit/docker-registry-ui/pull/319, am I missing something?

And while writing this, I think I understand, unlike in your test (https://github.com/Joxit/docker-registry-ui/pull/319/files#diff-702e29248f45a8a8d33d76ef028e6b85147aafab11751e0e215917ccf45523f3R73), I don't have images at the `docker.io/` level.

So if it's this, it's more of a feature request, could it be possible to force a first level?

## How to Reproduce

My docker-compose file
```yml
  registry-ui-joxit:
    image: docker.io/joxit/docker-registry-ui:2.5.6
    depends_on:
      - registry
    environment:
      TZ: *TZ
      SINGLE_REGISTRY: "true"
      PULL_URL: "https://..."
      NGINX_PROXY_PASS_URL: "..."
      NGINX_RESOLVER: "127.0.0.11"
      REGISTRY_TITLE: "My registry"
      DELETE_IMAGES: "true"
      SHOW_CONTENT_DIGEST: "true"
      SHOW_CATALOG_NB_TAGS: "true"
      #HISTORY_CUSTOM_LABELS: "label1,label2"
      CATALOG_DEFAULT_EXPANDED: "true"
      CATALOG_MIN_BRANCHES: "1"
      CATALOG_MAX_BRANCHES: "2"
```

My resulting HTML element
```html
<docker-registry-ui
      registry-url=""
      name="My registry"
      pull-url="https://my.registry"
      show-content-digest="true"
      is-image-remove-activated="true"
      catalog-elements-limit=""
      single-registry="true"
      default-registries=""
      read-only-registries=""
      show-catalog-nb-tags="true"
      history-custom-labels=""
      use-control-cache-header=""
      taglist-order=""
      catalog-default-expanded="true"
      catalog-min-branches="1"
      catalog-max-branches="2"
      is-registry-secured=""
      theme=""
      theme-primary-text=""
      theme-neutral-text=""
      theme-background=""
      theme-hover-background=""
      theme-accent-text=""
      theme-header-text=""
      theme-header-background=""
      theme-footer-text=""
      theme-footer-neutra-text=""
      theme-footer-background=""
      tags-per-page=""
    >
```

## Expected behavior

<img src="https://user-images.githubusercontent.com/5153882/242509633-41591e0a-3e15-4d87-ac93-44dcd88e6438.png">

## Screenshots

<img width="946" alt="image" src="https://github.com/Joxit/docker-registry-ui/assets/1735067/02003422-3dc3-4bf6-a9c9-0b5cefcd42db">
