### ISSUE TITLE
Cannot delete image in only one of the registries (missing delete icon)

### ISSUE THREAD

**Issue by tka85** [Joxit/docker-registry-ui#344]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I have three registries. For two of them I see the delete (trashcan) icon to delete images. For one of them I do not see it.

## How to Reproduce

My docker-compose file
```yml
reg-ui:
    container_name: reg-ui
    image: joxit/docker-registry-ui:2.5.3-debian
    environment:
      - SINGLE_REGISTRY=true
      - NGINX_PROXY_PASS_URL=http://reg:5000
      - REGISTRY_TITLE="Dealingo docker registry"
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
    depends_on:
      - reg
    expose:
      - 80
```

My private docker registry configuration
```yml
  reg:
    container_name: reg
    image: registry:2
    volumes:
      - ./reg/certs:/certs
      - ./reg/auth:/auth
      - reg-data:/var/lib/registry
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM="Bla bla"
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_HTTP_SECRET=${DOCKER_REGISTRY_HTTP_SECRET}
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    expose:
      - 5000
```

## Expected behavior

I'd expect to see trashcan icon next to the images of the third repo as well.

## Screenshots

Same as the one attached in [issue 123](https://github.com/Joxit/docker-registry-ui/issues/123)

## System information

- OS: Ubuntu 22.04
- Browser:
    - Name: Firefox 
    - Version: 117.0.1
- Docker registry UI:
    - Version: 2.5.3-debian
    - Server: docker
    - Docker version: Docker version 24.0.6, build ed223bc
    - Docker registry ui tag: 
    - OS/Arch: x64
    - Tools: docker-compose
