### ISSUE TITLE
CATALOG_NOT_FOUND with configuration nearly identical to example

### ISSUE THREAD

**Issue by evonicgu** [Joxit/docker-registry-ui#346]
Nearly copy-pasted the standard configuration, it works if using `REGISTRY_URL` with `https://mydomain.com`, but it fails because of CORS. But cannot get it working using `NGINX_PROXY_PASS_URL`, requests are not reaching the registry service.

`docker-compose.yml`:
```
version: '3.8'
services:
  registry-server:
    image: registry:2.8.2
    container_name: registry-server
    restart: unless-stopped
    volumes:
      - ./registry-data:/var/lib/registry
      - ./registry-config:/etc/docker/registry/
    ports:
      - "5000:5000"

  ui:
    restart: unless-stopped
    container_name: registry-ui
    image: joxit/docker-registry-ui:main
    ports:
      - "9090:80"
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry-server:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_ELEMENTS_LIMIT=1000
      - TAGLIST_PAGE_SIZE=100
      - THEME=auto
      - TAGLIST_ORDER=alpha-asc;num-desc
      - CATALOG_DEFAULT_EXPANDED=false
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - REGISTRY_SECURED=true
    depends_on:
      - registry-server
``` 

`registry-config/config.yml`:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://mydomain.com', '*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

`sudo netstat -tuplen | grep "(5000)|(9090)"`:
```
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      0          30658728   2273133/docker-prox
tcp        0      0 0.0.0.0:5000            0.0.0.0:*               LISTEN      0          30637744   2272979/docker-prox
tcp6       0      0 :::9090                 :::*                    LISTEN      0          30659697   2273140/docker-prox
tcp6       0      0 :::5000                 :::*                    LISTEN      0          30660760   2272987/docker-prox
```

`sudo docker ps`:
```
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                          PORTS                                        NAMES
2e052056aa01   joxit/docker-registry-ui:main   "/docker-entrypoint.…"   11 minutes ago   Up 11 minutes                   0.0.0.0:9090->80/tcp, :::9090->80/tcp        registry-ui
7450b1dbe84f   registry:2.8.2                  "/entrypoint.sh /etc…"   12 minutes ago   Up 11 minutes                   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp    registry-server
```
