### ISSUE TITLE
UI can't list tags if the registry use S3 backend.

### ISSUE THREAD

**Issue by BizA-Official** [Joxit/docker-registry-ui#355]
Hi everyone!

I migrated my registry's data to s3 and I experience a very interesting issue.

On the main page of the UI, I can see how many tags I have under an image, however it can't list them:S
<img width="1387" alt="ui1" src="https://github.com/Joxit/docker-registry-ui/assets/137334142/e3a791c9-2dce-4c1b-84a7-a7707eb5d65f">
<img width="1458" alt="ui2" src="https://github.com/Joxit/docker-registry-ui/assets/137334142/ba286037-adf1-4a14-b471-9109a7c161b1">

I have not received any error message.

Here is my docker-compose.yml file:
```
version: '3.8'
services:
  registry:
    image: registry:latest
    ports:
    - "45000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
      - ./auth:/auth
      - ./config.yml:/etc/docker/registry/config.yml
      - ./data:/var/lib/registry
    restart: always
    networks:
      - local


  registry-ui:
    image: joxit/docker-registry-ui:main
    restart: always
    ports:
      - 45480:80
    environment:
      - REGISTRY_URL=https://registry-ui.example.com
      - SINGLE_REGISTRY=false
      - REGISTRY_TITLE=Otthonzona Docker Registry
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://docker-registry-registry-1:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    networks:
      - local
networks:
  local:
    name: docker-registry_default
    external: true
```

And my config.yml file:
```
version: 0.1

log:
  level: debug
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: accesskey
    secretkey: secretkey
    region: "minio-s3-1"
    regionendpoint: "minio-s3-1.example.com"
    bucket: docker-registry
    encrypt: false
    secure: true
    v4auth: true
    chunksize: 5242880
    rootdirectory: /data
  redirect:
    disable: true
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['*']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```

My S3 allows CORS from *
