### ISSUE TITLE
Delete Tag: The operation is unsupported.

### ISSUE THREAD

**Issue by pcace** [Joxit/docker-registry-ui#381]
HI there, waht can be the reason not to be able to delete images via the ui? 
whenever i click on delete on a tag, i get this error Message: 

`{"errors":[{"code":"UNSUPPORTED","message":"The operation is unsupported."}]}
`
I run the docker-registry-ui with these env variables: 

SINGLE_REGISTRY=true
REGISTRY_TITLE=Docker Registry UI
DELETE_IMAGES=true
SHOW_CONTENT_DIGEST=true
NGINX_PROXY_PASS_URL=http://registry:5000
SHOW_CATALOG_NB_TAGS=true
CATALOG_MIN_BRANCHES=1
CATALOG_MAX_BRANCHES=1
TAGLIST_PAGE_SIZE=100
REGISTRY_SECURED=false
CATALOG_ELEMENTS_LIMIT=1000
REGISTRY_STORAGE_DELETE_ENABLED=true

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

```
![image](https://github.com/Joxit/docker-registry-ui/assets/1011875/8b066735-f7ab-4dbd-8502-e9f7f6e430eb)

## System information

- OS: Debian
- Browser:
    - Name: Chrome
    - Version: Version 125.0.6422.60 (Offizieller Build) (64-Bit)

- Docker registry UI:
    - Version: joxit/docker-registry-ui:main
    -  Server: docker
    - Docker version: Docker version 26.1.2, build 211e74b
    - Docker registry ui tag: main
    - OS/Arch:  Debian12 /amd64
