### ISSUE TITLE
Question about setting up connection with registry over https

### ISSUE THREAD

**Issue by alexanderbazhenoff** [Joxit/docker-registry-ui#384]
Hi, I use this docker registry UI and I have an issue... or may be it's just a question how to set-up.

I have a registry with openssl generated certs as described [here](https://github.com/justmeandopensource/docker/blob/master/docker-compose-files/docker-registry/docs/Generate%20certificates%20for%20TLS%20registry.md):

```yaml
---
services:

  # Configuring registry server: https://github.com/GerritForge/docker-registry/blob/master/docs/configuration.md
  registry-server:
    image: registry:latest
    restart: always
    ports:
      - 5000:443
    environment:
      REGISTRY_HTTP_ADDR: '0.0.0.0:443'
      REGISTRY_HTTP_TLS_CERTIFICATE: '/opt/certs/domain.crt'
      REGISTRY_HTTP_TLS_KEY: '/opt/certs/domain.key'
      REGISTRY_AUTH_HTPASSWD_REALM: 'basic-realm' # or 'Registry-Realm'
      REGISTRY_AUTH_HTPASSWD_PATH: '/etc/docker/registry/auth/passwdfile'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_HEADERS_X-Content-Type-Options: '[nosniff]'
      REGISTRY_HTTP_HEADERS_Access-Control-Max-Age: '[1728000]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[https://localhost:5000]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
    volumes:
      - ./data/registry-ui:/var/lib/registry
      - ./certs:/opt/certs
      - ./passwdfile:/etc/docker/registry/auth/passwdfile:ro
    container_name: registry-server
```
I also made some tests, e.g:

```bash
#!/usr/bin/env bash

set -ex
curl -sk https://reg.dev:5000/v2/_catalog --user username:password
skopeo copy --all docker://mirror.gcr.io/alpine docker://reg.dev:5000/alpine/alpine \
  --dest-creds username:password
docker login reg.dev:5000 -u=username --password-stdin <<< 'password'
docker pull reg.dev:5000/alpine/alpine
skopeo delete docker://reg.dev:5000/alpine/alpine:latest
```

Registry works fine.

Then I set up UI:

```yaml
  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - 80:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE="Docker Registry UI"
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://registry-server:5000
      - REGISTRY_URL=https://localhost:5000
      - NGINX_PROXY_HEADER_X_Forwarded_For=$$proxy_add_x_forwarded_for
      - REGISTRY_SSL=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.env:/etc/nginx/.env
    depends_on:
      - registry-server
```

When I open `http://localhost/` or `http://reg/` **I got an error**:

> The `Access-Control-Allow-Credentials` header in the response is missing and must be set to `true` when the request's credentials mode is on. Origin `https://localhost:5000` is therefore not allowed access.

I also tried [this](https://github.com/Joxit/docker-registry-ui/tree/main/examples/proxy-headers) auth suggestion:

```bash
NGINX_PROXY_HEADER_Authorization=Basic <`echo -n "username:password" | base64` command output>
```

Nothing changed.

Can you please help me to set up connection betwen registry and UI?
Thanks for any information in advance.
