### ISSUE TITLE
Cors error when looking at details of image

### ISSUE THREAD

**Issue by Paultje52** [Joxit/docker-registry-ui#385]
## Bug description
I'm getting a cors error when visiting the page of a specifc image.

## How to Reproduce

My docker-compose file
```yml
version: '3'

services:
  registry:
    restart: always
    image: registry:2
    ports:
    - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./auth:/auth
      - ./data:/data
      - ./config.yml:/etc/docker/registry/config.yml

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 5001:80
    environment:
      - REGISTRY_TITLE=Docker Registry
      - REGISTRY_URL=some_url
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
```

My private docker registry configuration
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
    delete:
      enabled: true
http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['https://docker-ui.paultje52.me']
    Access-Control-Allow-Methods: ['GET', 'OPTIONS', 'HEAD']
    Access-Control-Allow-Headers: ['Authorization']
    Access-Control-Allow-Credentials: [true]
```

## Expected behavior
I would expect the page to load and show all the relevant information

## Screenshots
![image](https://github.com/Joxit/docker-registry-ui/assets/31313717/131483cd-e8ad-4ba3-b536-80d1db581ea7)
![image](https://github.com/Joxit/docker-registry-ui/assets/31313717/1174ff70-61c9-4cc4-b433-b3bc1b6abf8f)

Note: the main page (with the catalog request) works without any problems.
![image](https://github.com/Joxit/docker-registry-ui/assets/31313717/52469df8-963d-4dd6-b72f-c66b96c90f98)

## System information

- OS: Ubuntu (debian)
- Browser:
    - Name: Chrome
    - Version: 125.0.6422.142
- Docker registry UI:
    - Version: Latest (v2)
    - Server: docker
    - Docker version: 26.1.4, build 5650f9b
    - Docker registry ui tag: latest
    - OS/Arch: linux/amd64
    - Tools: docker-compose
