### ISSUE TITLE
How to get default registries working? (getting CORS issue)

### ISSUE THREAD

**Issue by bekraupov** [Joxit/docker-registry-ui#403]
hi,

we have few internal registries we would like to expose using this registry UI. 

below are the values we are setting:

```yaml
iu.proxy: false
- name: DEFAULT_REGISTRIES
              value: "https://reg1.example.com,https://reg2.example.com"
registry.enabled: false 
```

and we dont have "registry option enabled" (so running just UI). 

UI is opening up, but when we try to access it, I can see we are getting CORS error in network tab (in Chrome):
```bash
Access to XMLHttpRequest at 'https://reg1.example.com/v2/_catalog?n=1000' from origin 'https://AAA.BBB' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

What's the way out?  I have tried to manually update nginx default.conf with "add-header" commands but no luck.
