### ISSUE TITLE
Unauthorized and CORS errors while login succesfull. 

### ISSUE THREAD

**Issue by ozersenol** [Joxit/docker-registry-ui#404]
Hi all, I am getting UnAuthorized error but at the same time auth is 200 OK!  CORS error. I am using nginx-proxy-manager that registry redirects 5000 port w,th https: https://registry.athlantys.com and 5001 port with http: registry-hub.athlantys.com 

![Screenshot 2024-11-30 123336](https://github.com/user-attachments/assets/eb2bd474-8679-4931-bb66-c6c813e6c378)
![Screenshot 2024-11-30 123413](https://github.com/user-attachments/assets/78472744-4e71-4f09-87b9-435b40febf16)

I can login and display repos but cannot see time, size and digest info and cannot delete images.

![Screenshot 2024-11-30 124046](https://github.com/user-attachments/assets/60f2a4b0-9cc4-4fc1-8408-da2200b74b9f)

My docker-compose.yml is: 

```
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/server.crt
      REGISTRY_HTTP_TLS_KEY: /certs/server.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[https://registry-hub.athlantys.com]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./auth:/auth
    container_name: registry
    networks:
      - registry-ui-net

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "5001:80"
    environment:
      - REGISTRY_URL=https://registry.athlantys.com
      - REGISTRY_AUTH=true
      - REGISTRY_AUTH_FILE=/auth/htpasswd
      - REGISTRY_AUTH_TYPE= basic
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=ATHLANTYS
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - NGINX_PROXY_PASS_URL=http://registry:5000
    volumes:
      - ./auth/htpasswd:/auth/htpasswd:ro
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net:
```

Any help is appreciated! Thanks.
