### ISSUE TITLE
Icons for ascending & descending are not shown correctly

### ISSUE THREAD

**Issue by feliwir** [Joxit/docker-registry-ui#406]
Hi, I use this docker registry UI and I have an issue...

## Bug description

I can't see the icons when entering the image details page. A placeholder is displayed instead:

## How to Reproduce

1. Select an image from the list
2. It will only show icons placegolders

My docker-compose file
```yml
services:
  registry:
    image: registry:2.8.3
    restart: always
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
      - ./config/auth:/auth
      - ./config/data:/var/lib/registry
      - ./config/credentials.yml:/etc/docker/registry/config.yml
    container_name: registry

  registry-ui:
    image: joxit/docker-registry-ui:2.5.7
    restart: always
    ports:
      - 80:80
    depends_on:
      - registry
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry
      - REGISTRY_URL=http://localhost:5000
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
```

My credentials.yml
```yml
version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://localhost']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
```

## Expected behavior

See the correct icons there

## Screenshots

![image](https://github.com/user-attachments/assets/15f575c1-9951-4924-8aa0-a525b27e9e72)

## System information

- OS: [e.g. Debian, Windows, Mac OS, Android 9...]
- Browser:
    - Tested both Firefox & Chrome 
- Docker registry UI:
    - Version:Tested 2.5.7 and main
    - Server: docker
    - Docker version: 27.4.0, build bde2b89
    - OS/Arch: [Fedora Linux]
    - Tools: docker-compose
