### ISSUE TITLE
UI doesn't ask for user and password

### ISSUE THREAD

**Issue by juan-ferrer-toribio** [Joxit/docker-registry-ui#424]
When using `docker_auth` (https://github.com/cesanta/docker_auth) the UI doesn't ask for user and password for deleting images when anonymous read access is allowed to the registry.

I suggest to add `req.withCredentials = true;` to auth URL when bearer is passed but registry responds with 401.

**Comment by Joxit** [comment]
Hi, thank you for using my project and submitting issues.

Could you share your minimum configuration so I can reproduce your issue?

**Comment by viesturseihentals-saf** [comment]
I am facing similar issues with GitLab as auth provider.
My config is something like [this](https://github.com/ipernet/gitlab-docs/blob/master/gitlab-registry.md):
```yaml
auth:
  token:
    realm: https://gitlab.example.com/jwt/auth
    service: container_registry
    issuer: gitlab-issuer
    rootcertbundle: /root/certs/certbundle
```
I feel like Juan is right and there should be a way to catch the 401 and display an input box. Once the user has submitted their auth providers credentials, and it responded with the bearer token, it would be a matter of using it for the registry requests in a similar way as you do with Basic auth.

**Comment by juan-ferrer-toribio** [comment]
Hi @ppar ,

Without anonymous user I got it working but I need anonymous **read** access since my registry is public, but also I need authenticated delete access.

@Joxit I've deployed UI with bare standard config using Helm, nothing special:
```yaml
ui:
  image: joxit/docker-registry-ui:2.5.6
  title: "My registry"
  dockerRegistryUrl: https://registry.mydomain.org
  registrySecured: true
  deleteImages: true
  ingress:
    enabled: true
    host: registry.mydomain.org
registry:
  enabled: true
  image: registry:2.8.3
  dataVolume:
    persistentVolumeClaim:
      claimName: registry-data
  auth:
    token:
      autoredirect: false
      issuer: "docker-auth"
      realm: "https://registry.mydomain.org/auth"
      service: "docker-registry"
      rootcertbundle: /rootcertbundle.pem
  ingress:
    enabled: true
    host: registry.mydomain.org
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: '0'
```

With the following [cesanta/docker_auth](https://github.com/cesanta/docker_auth) config.
```yaml
token:
  issuer: "docker-auth"
  expiration: 86400
users:
  "": {}
  admin:
    password: "$2y$05$***"
acl:
  - match: { account: "admin", ip: "10.0.0.0/8" }
    actions: ["*"]
    comment: "Admin has full access to everything."
  - match: { account: "", type: "registry", name: "catalog"}
    actions: ["*"]
    comment: "Anonymous user can query the registry"
  - match: { account: "" }
    actions: ["pull"]
    comment: "Anonymous user can pull"
```
