### ISSUE TITLE
Does not show creation date

### ISSUE THREAD

**Issue by andyceo** [Joxit/docker-registry-ui#52]
Hi!

Thanks for that greate project!

Works well, but I can not see any info about image creation date:

![default](https://user-images.githubusercontent.com/758910/48919396-ac253680-eea3-11e8-8c23-03ae6941ce61.png)

How to fix that?

I used v0.5.0

**Comment by andyceo** [comment]
This is fresh install of 0.5.0:static. Private mode give same results (no creation date). I use following docker swarm stack to deploy registry + ui:

```
  registry:
    image: registry:2.6
    volumes:
      - /data/registry:/var/lib/registry
    networks:
      - registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "True"

  dockerui:
    image: joxit/docker-registry-ui:static
    networks:
      - nginx
      - registry
    environment:
      REGISTRY_URL: http://infrastructure_registry:5000
      DELETE_IMAGES: "true"
      REGISTRY_TITLE: DockerUI
```

And nginx route all requests:

```
    location / {
        allow 192.168.2.0/24;
        deny all;
        proxy_pass http://dockerui;
    }
```

All the requests from page goes ok to the server:

![image](https://user-images.githubusercontent.com/758910/48951693-8e61db00-ef50-11e8-8d7d-aa2f9af9d06f.png)
