### ISSUE TITLE
UI blank?

### ISSUE THREAD

**Issue by LunaticZorr** [Joxit/docker-registry-ui#74]
Hi!

I just deployed the Docker Registry and Joxit, but when I browse to it I just get a blank page. The UI container starts and I can see the source code of the website:

```
<!--
 Copyright (C) 2016-2019 Jones Magloire @Joxit

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
--><!DOCTYPE html><html><head><meta charset="UTF-8"><link rel="stylesheet" href="vendor.css"><link rel="stylesheet" href="style.css"><link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet" type="text/css"><meta name="viewport" content="width=device-width,initial-scale=1"><meta property="og:site_name" content="Docker Registry UI"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@Joxit"><meta name="twitter:creator" content="@Jones Magloire"><title>Docker Registry UI</title></head><body><app></app><script src="scripts/vendor.js"></script><script src="scripts/docker-registry-ui.js"></script></body></html>
```

But can't see anything else. 

My Apache config:
```
<VirtualHost *:443>

    # Servername / domain

    ServerName registry.domain.com

    # Enable SSL and SSLProxy

    SSLEngine On
    SSLProxyEngine On

    # Set the path to SSL certificate

    SSLCertificateFile /etc/letsencrypt/live/registry.domain.com/domain.crt
    SSLCertificateKeyFile /etc/letsencrypt/live/registry.domain.com/domain.key

    # Higher Strength SSL Ciphers

    SSLProtocol all -SSLv2 -SSLv3 -TLSv1
    SSLCipherSuite RC4-SHA:HIGH
    SSLHonorCipherOrder on

    # Headers

    Header always set "Docker-Distribution-Api-Version" "registry/2.0"
    Header onsuccess set "Docker-Distribution-Api-Version" "registry/2.0"
    RequestHeader set X-Forwarded-Proto "https"

    # Proying

    ProxyRequests     off
    ProxyPreserveHost on
    ProxyPass /error/ !

    # Proxy /v2 to the Registry container

    ProxyPass        /v2 https://localhost:5000/v2
    ProxyPassReverse /v2 https://localhost:5000/v2

    ProxyPass        /ui http://localhost:5001
    ProxyPassReverse /ui http://localhost:5001

    # Logs

    ErrorLog ${APACHE_LOG_DIR}/registry-error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/registry-access.log combined

</VirtualHost>
```

How I start the Registry:

```
docker run -d -p 5000:443 --restart=always --name registry \
  -v /etc/letsencrypt/live/registry.domain.com:/certs \
  -v /mnt/docker-registry:/var/lib/registry \
  -v /mnt/docker-registry/config.yml:/etc/docker/registry/config.yml \
  -e REGISTRY_HTTP_ADDR=0.0.0.0:443 \
  -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
  -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
  -e REGISTRY_AUTH=htpasswd \
  -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
  -e REGISTRY_AUTH_HTPASSWD_PATH=/var/lib/registry/passfile \
  registry:latest
```

Registry config:
```
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://127.0.0.1:8001']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
```
And how I start the UI:

```
docker run -d -p 5001:80 --name ui \
-e REGISTRY_TITLE="Docker Registry" \
-e DELETE_IMAGES=true \
-e REGISTRY_URL=https://localhost:5000 \
joxit/docker-registry-ui:static
```

What am I missing?

THANKS!
