### ISSUE TITLE
Help with insecure config

### ISSUE THREAD

**Issue by RANGERBEE** [Joxit/docker-registry-ui#76]
Hey Joxit,

  Thanks for quick and slick UI that just plain works!

Can you tell me how to get an insecure configuration working. I just cant seem to figure out how to push or pull from a docker client. I get https errors.. I know its probably because no TLS certs are loaded on either side. I would like s simple insecure registry is all.

Could you help with a quick config?

### Running the docker compose "credentials" file out of examples/ui-as-proxy to get all spun up.

Thanks!!

**Comment by RANGERBEE** [comment]
I have fixed with the following simple.yml

```yaml
version: '2.0'
services:
  registry:
    image: registry:2.6.2
    volumes:
      - ./registry-data:/var/lib/registry
    ports:
      - 5000:5000
    networks:
      - docker-registry-ui
    environment:
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=['*']

  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=My Private Docker Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - docker-registry-ui

networks:
  docker-registry-ui:
```

AND on remote docker client making the PUSH...

I get helped from [http://stackoverflow.com/questions/38695515/can-not-pull-push-images-after-update-docker-to-1-12], two steps in total to solve this issue:

Create or modify /etc/docker/daemon.json
` { "insecure-registries":["myregistry.example.com:5000"] }`
```console
Restart docker daemon
sudo service docker restart
```
 I hope this may help others.

Thank you again for the simple and effective UI to the registry!
