### ISSUE TITLE
UI as a Proxy seems to query itself?

### ISSUE THREAD

**Issue by whillas** [Joxit/docker-registry-ui#91]
Hey,
I'm using the `examples/ui-as-proxy/simple.yml` example. Here is my config:
```yaml
version: '3'
services:
    registry:
        image: registry:2.7.1
        restart: always
        ports:
            - "6666:5000"
        environment:
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
        volumes:
            - /datasets/docker-registry/data:/data
        networks:
            - registry-ui-net
    ui:
        image: joxit/docker-registry-ui:static
        restart: always
        ports:
            - 8080:80
        environment:
            - REGISTRY_TITLE=Example Local Docker Registry
            - REGSITRY_URL=http://registry:6666
        depends_on:
            - registry
        networks:
            - registry-ui-net

networks:
  registry-ui-net:
```
Looking at the HTTP headers it seems to think that the registry is running on `http://192.168.1.84:8080/v2/_catalog?n=100000`? Which is the UI?
